apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    component: vault
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: vault
