groups:
  - name: somaagent-alerts
    rules:
      - alert: TelemetryWorkerDown
        expr: up{job="telemetry_worker"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Telemetry worker offline"
          description: "Prometheus has not scraped telemetry_worker for 1 minute."
      - alert: DelegationGatewayDown
        expr: up{job="delegation-gateway"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Delegation gateway unreachable"
          description: "No successful scrapes for delegation-gateway job in the last 2 minutes."
      - alert: DelegationGatewayHighErrorRate
        expr: |
          sum(rate(delegation_gateway_requests_total{status=~"5.."}[5m]))
            /
          clamp_min(sum(rate(delegation_gateway_requests_total[5m])), 1) > 0.05
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Delegation gateway error rate above 5%"
          description: "5xx responses from delegation gateway exceeded 5% over the last 10 minutes."
      - alert: DelegationGatewayHighLatencyP95
        expr: histogram_quantile(
                0.95,
                sum by (le) (rate(delegation_gateway_request_duration_seconds_bucket[5m]))
              ) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Delegation gateway p95 latency above 1s"
          description: "95th percentile request latency has stayed above 1s for 10 minutes."
      - alert: OpenfgaDown
        expr: up{job="openfga"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "OpenFGA exporter unreachable"
          description: "Prometheus cannot scrape the OpenFGA metrics endpoint."
      - alert: OpaDown
        expr: up{job="opa"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "OPA metrics endpoint unreachable"
          description: "Open Policy Agent has not responded to scrapes for 2 minutes."
      - alert: SomaAgentHubUnavailable
        expr: min_over_time(soma_agent_hub_up[1m]) < 1
        for: 1m
        labels:
          severity: critical
          service: soma-agent-hub
        annotations:
          summary: "SomaAgentHub OpenAPI endpoint unreachable"
          description: "Gateway probes to the SomaAgentHub OpenAPI endpoint have failed for at least 1 minute."
      - alert: DelegationQueueBacklog
        expr: avg_over_time(delegation_gateway_tasks_inflight[5m]) > 5
        for: 5m
        labels:
          severity: warning
          service: delegation-gateway
        annotations:
          summary: "Delegation queue depth growing"
          description: "Delegation gateway has more than 5 tasks in-flight for 5 minutes. Investigate stuck delegation workers."
      - alert: SessionEnvelopeRefreshErrors
        expr: increase(session_envelope_refresh_total{result="error"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
          service: session-state
        annotations:
          summary: "Session envelope refresh failures detected"
          description: "Postgres refreshes for session envelopes are failing. Inspect database connectivity and recent cache misses."
      - alert: SessionEnvelopeMissingSpike
        expr: |
          (increase(session_envelope_refresh_total{result="missing"}[10m]) / clamp_min(increase(session_envelope_refresh_total[10m]), 1)) > 0.5
        for: 10m
        labels:
          severity: warning
          service: session-state
        annotations:
          summary: "High rate of missing session envelopes"
          description: "More than half of refresh attempts are missing envelopes over the last 10 minutes. Validate backfill coverage and cache hydration."
      - alert: SessionEnvelopeValidationFailures
        expr: sum(rate(session_envelope_validation_failures_total[5m])) > 0
        for: 5m
        labels:
          severity: warning
          service: session-state
        annotations:
          summary: "Session envelope validation failures detected"
          description: "Session metadata payloads are failing validation for at least 5 minutes. Check gateway inputs and schema alignment."
      - alert: SessionEnvelopeCacheErrors
        expr: increase(session_envelope_cache_events_total{operation="set", result="error"}[5m]) > 0
        for: 5m
        labels:
          severity: warning
          service: session-state
        annotations:
          summary: "Session envelope cache writes failing"
          description: "Redis writes for session envelopes are erroring. Inspect cache connectivity and Redis health."
      # New alerts for gateway latency > 2 seconds (95th percentile) and error‑rate > 1%
      - alert: GatewayHighLatencyP95
        expr: |
          histogram_quantile(
            0.95,
            sum by (le) (rate(gateway_request_latency_seconds_bucket[5m]))
          ) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Gateway request latency > 2 s (p95)"
          description: "The 95th percentile latency for gateway requests has been above 2 seconds for the last 5 minutes."
      - alert: GatewayHighErrorRate
        expr: |
          sum(rate(gateway_requests_total{status=~"5.."}[5m]))
            /
          clamp_min(sum(rate(gateway_requests_total[5m])), 1) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Gateway error rate > 1 %"
          description: "More than 1 % of gateway requests returned 5xx errors over the last 5 minutes."
