global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8000']
  - job_name: 'telemetry_worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['telemetry-worker:8020']
