kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: soma
nodes:
  - role: control-plane
    extraPortMappings:
      # Expose app gateway via NodePort 30080 -> host 7002
      - containerPort: 30080
        hostPort: 7002
        listenAddress: 127.0.0.1
        protocol: TCP
  - role: worker