# staging-values.yaml – staging configuration
# Use with environment=staging to validate TLS against Let's Encrypt staging.

global:
  DEPLOY_MODE: dev_prod
  JWT_ENABLED: true
  OPA_ENABLED: true
  MTLS_ENABLED: true
  REPLICA_COUNT: 2
  RESOURCE_REQUESTS:
    cpu: 250m
    memory: 256Mi
  RESOURCE_LIMITS:
    cpu: 500m
    memory: 512Mi
  ISTIO_INJECTION: true
  VAULT_AGENT_INJECT: true
  PROMETHEUS_SCRAPE: true
  OTEL_ENABLED: true
  NETWORK_POLICY_ENABLED: true
  CERT_MANAGER_CLUSTER_ISSUER: letsencrypt-staging

services:
  gateway:
    ingress:
      enabled: true
      className: nginx
      host: gateway.staging.soma.internal
      path: /
      annotations: {}
      tls:
        - hosts: [gateway.staging.soma.internal]
          secretName: gateway-staging-tls
    istio:
      enabled: false
      host: gateway.staging.soma.internal
      gateways: ["istio-system/public-gateway"]
  ui:
    ingress:
      enabled: true
      className: nginx
      host: ui.staging.soma.internal
      path: /
      annotations: {}
      tls:
        - hosts: [ui.staging.soma.internal]
          secretName: ui-staging-tls
  uiProxy:
    ingress:
      enabled: true
      className: nginx
      host: uip.staging.soma.internal
      path: /
      annotations: {}
      tls:
        - hosts: [uip.staging.soma.internal]
          secretName: uip-staging-tls
