# Generated by Django 5.1.4 on 2026-09-27 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aaas", "0004_platformconfig_delete_globaldefault_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Stable module id from module.yaml (e.g. mod_whatsapp)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Real toggle state; always_enabled modules are forced on",
                    ),
                ),
                (
                    "always_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Core modules that cannot be disabled through the API",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Runtime module.config.json values (Capsule overrides in persona_config)",
                    ),
                ),
                (
                    "settings_sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UI sections contributed: agent|external|developer|mcp|backup|file-browser|skills",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True, default=list, help_text="Declared permissions from module.yaml"
                    ),
                ),
                (
                    "feature_flag",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="FeatureRegistry key required before this module can be enabled",
                        max_length=100,
                    ),
                ),
                (
                    "manifest",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full parsed module.yaml snapshot"
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Filesystem directory of the module (built-in path or install path)",
                        max_length=512,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional tenant binding; NULL = platform-wide module",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capsule_modules",
                        to="aaas.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "capsule_modules",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["enabled"], name="capsule_mod_enabled_c7b30a_idx"),
                    models.Index(fields=["tenant", "name"], name="capsule_mod_tenant__9f5a6d_idx"),
                ],
            },
        ),
    ]
