"""Module 0001_initial."""

# Generated by Django 5.1.4 on 2025-12-23 19:58

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Migration class implementation."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaasFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique feature code (e.g., 'voice', 'memory', 'mcp')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Feature description for UI"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("voice", "Voice & Speech"),
                            ("memory", "Memory & Context"),
                            ("mcp", "MCP Servers"),
                            ("vision", "Vision & Image"),
                            ("models", "AI Models"),
                            ("browser", "Browser Automation"),
                            ("code_exec", "Code Execution"),
                            ("tools", "Tool Access"),
                            ("delegation", "Agent Delegation"),
                        ],
                        db_index=True,
                        help_text="Feature category for grouping",
                        max_length=30,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="settings",
                        help_text="Google Material Symbol icon name",
                        max_length=50,
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        blank=True, default=dict, help_text="JSON Schema for feature configuration"
                    ),
                ),
                (
                    "default_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default settings when feature is enabled",
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=False, help_text="Whether feature has usage-based billing"
                    ),
                ),
                (
                    "lago_billable_metric_code",
                    models.CharField(
                        blank=True,
                        help_text="Lago billable metric code for usage tracking",
                        max_length=100,
                    ),
                ),
                (
                    "requires_modal",
                    models.BooleanField(
                        default=True, help_text="Whether feature requires full-screen config modal"
                    ),
                ),
                (
                    "modal_component",
                    models.CharField(
                        blank=True,
                        help_text="Lit component name for settings modal",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether feature is available for configuration",
                    ),
                ),
                (
                    "is_beta",
                    models.BooleanField(default=False, help_text="Whether feature is in beta"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order in feature catalog"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SAAS Feature",
                "verbose_name_plural": "SAAS Features",
                "db_table": "saas_features",
                "ordering": ["category", "sort_order", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="saas_featur_code_334a9a_idx"),
                    models.Index(fields=["category"], name="saas_featur_categor_92cec1_idx"),
                    models.Index(fields=["is_active"], name="saas_featur_is_acti_ed3142_idx"),
                    models.Index(fields=["sort_order"], name="saas_featur_sort_or_e4e562_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tier display name (e.g., 'Starter', 'Team', 'Enterprise')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(help_text="URL-safe identifier", unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Marketing description for the tier"),
                ),
                (
                    "base_price_cents",
                    models.BigIntegerField(
                        default=0, help_text="Base monthly price in cents (USD)"
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("weekly", "Weekly"),
                        ],
                        default="monthly",
                        help_text="Billing cycle",
                        max_length=20,
                    ),
                ),
                (
                    "lago_plan_code",
                    models.CharField(
                        blank=True, help_text="Lago billing plan code", max_length=100
                    ),
                ),
                ("max_agents", models.IntegerField(default=1, help_text="Maximum agents allowed")),
                (
                    "max_users_per_agent",
                    models.IntegerField(default=5, help_text="Maximum users per agent"),
                ),
                (
                    "max_monthly_voice_minutes",
                    models.IntegerField(default=60, help_text="Monthly voice minutes allowance"),
                ),
                (
                    "max_monthly_api_calls",
                    models.IntegerField(default=1000, help_text="Monthly API calls allowance"),
                ),
                (
                    "max_storage_gb",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Storage allowance in GB",
                        max_digits=10,
                    ),
                ),
                (
                    "feature_defaults",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default feature configurations for this tier",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this tier is available for new subscriptions",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether tier is shown on public pricing page"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order on pricing page"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Tier",
                "verbose_name_plural": "Subscription Tiers",
                "db_table": "subscription_tiers",
                "ordering": ["sort_order", "base_price_cents"],
                "indexes": [
                    models.Index(fields=["slug"], name="subscriptio_slug_03cc71_idx"),
                    models.Index(fields=["is_active"], name="subscriptio_is_acti_a7d112_idx"),
                    models.Index(fields=["sort_order"], name="subscriptio_sort_or_3b0519_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Organization name", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for tenant", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Activation"),
                            ("churned", "Churned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "keycloak_realm",
                    models.CharField(
                        blank=True, help_text="Keycloak realm for this tenant", max_length=100
                    ),
                ),
                (
                    "lago_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Lago customer external ID",
                        max_length=100,
                    ),
                ),
                (
                    "lago_subscription_id",
                    models.CharField(
                        blank=True, help_text="Lago subscription external ID", max_length=100
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, help_text="Primary billing contact email", max_length=254
                    ),
                ),
                (
                    "feature_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-tenant feature configuration overrides",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Arbitrary metadata for integrations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trial_ends_at",
                    models.DateTimeField(blank=True, help_text="When trial period ends", null=True),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        help_text="Current subscription tier",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="saas.subscriptiontier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "actor_id",
                    models.UUIDField(db_index=True, help_text="User ID who performed the action"),
                ),
                (
                    "actor_email",
                    models.EmailField(
                        blank=True, help_text="Actor email (denormalized for query)", max_length=254
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action type (e.g., 'tenant.created', 'tier.updated')",
                        max_length=100,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Resource type affected (e.g., 'tenant', 'agent', 'tier')",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        blank=True, db_index=True, help_text="ID of affected resource", null=True
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="Previous state (for updates)", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="New state (for creates/updates)", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Request IP address", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="Request user agent")),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Correlation ID for request tracing",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="saas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Agent display name", max_length=100)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier within tenant", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Agent purpose/description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Agent-specific configuration"
                    ),
                ),
                (
                    "feature_settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Feature configuration for this agent"
                    ),
                ),
                (
                    "skin_id",
                    models.UUIDField(blank=True, help_text="Associated skin/theme ID", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="saas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "db_table": "agents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, help_text="Keycloak user ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="User email (denormalized from Keycloak)", max_length=254
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, help_text="User display name", max_length=200),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="saas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant User",
                "verbose_name_plural": "Tenant Users",
                "db_table": "tenant_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TierFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether feature is enabled for this tier"
                    ),
                ),
                (
                    "settings_override",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tier-specific settings that override feature defaults",
                    ),
                ),
                (
                    "quota_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Usage quota limit for this tier (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "quota_policy",
                    models.CharField(
                        choices=[
                            ("hard", "Hard Block"),
                            ("soft", "Soft Warn"),
                            ("none", "Unlimited"),
                        ],
                        default="soft",
                        help_text="How quota is enforced",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_assignments",
                        to="saas.saasfeature",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_features",
                        to="saas.subscriptiontier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier Feature",
                "verbose_name_plural": "Tier Features",
                "db_table": "saas_tier_features",
                "ordering": ["tier", "feature"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "metric_code",
                    models.CharField(
                        db_index=True,
                        help_text="Billable metric code (e.g., 'voice_minutes', 'api_calls')",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, help_text="Usage quantity", max_digits=20
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="units", help_text="Unit of measurement", max_length=20
                    ),
                ),
                (
                    "lago_event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Lago event transaction ID",
                        max_length=100,
                    ),
                ),
                (
                    "lago_synced",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Whether synced to Lago"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context for the usage event"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When usage was recorded"
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(blank=True, help_text="Start of usage period", null=True),
                ),
                (
                    "period_end",
                    models.DateTimeField(blank=True, help_text="End of usage period", null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="saas.agent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="saas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "db_table": "usage_records",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, help_text="Keycloak user ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                        ],
                        default="operator",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_users",
                        to="saas.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent User",
                "verbose_name_plural": "Agent Users",
                "db_table": "agent_users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="agent_users_user_id_c30b77_idx"),
                    models.Index(fields=["role"], name="agent_users_role_487704_idx"),
                ],
                "unique_together": {("agent", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="FeatureProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique provider code (e.g., 'elevenlabs', 'openai_whisper')",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Provider description")),
                (
                    "config_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema for provider-specific configuration",
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default configuration for this provider",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default provider for the feature",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="saas.saasfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Provider",
                "verbose_name_plural": "Feature Providers",
                "db_table": "saas_feature_providers",
                "ordering": ["feature", "-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["feature", "is_active"], name="saas_featur_feature_89e37b_idx"
                    ),
                    models.Index(fields=["code"], name="saas_featur_code_be8fe3_idx"),
                ],
                "unique_together": {("feature", "code")},
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="tenants_status_80d9b6_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["lago_customer_id"], name="tenants_lago_cu_496f04_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["-created_at"], name="tenants_created_5c5edb_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor_id", "created_at"], name="audit_logs_actor_i_5bd818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="audit_logs_tenant__0b1a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="audit_logs_action_391715_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="audit_logs_resourc_bda8a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-created_at"], name="audit_logs_created_43fcd6_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["tenant", "status"], name="agents_tenant__fad503_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["status"], name="agents_status_f5ff61_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["-created_at"], name="agents_created_a7b1cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="agent",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["user_id"], name="tenant_user_user_id_f93ec7_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["email"], name="tenant_user_email_756120_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["role"], name="tenant_user_role_00f530_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["is_active"], name="tenant_user_is_acti_a9afac_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tenantuser",
            unique_together={("tenant", "user_id")},
        ),
        migrations.AddIndex(
            model_name="tierfeature",
            index=models.Index(
                fields=["tier", "is_enabled"], name="saas_tier_f_tier_id_6c682b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tierfeature",
            index=models.Index(fields=["feature"], name="saas_tier_f_feature_d87b80_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tierfeature",
            unique_together={("tier", "feature")},
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "metric_code"], name="usage_recor_tenant__b17ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "recorded_at"], name="usage_recor_tenant__d7582d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(fields=["lago_synced"], name="usage_recor_lago_sy_da0de7_idx"),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["metric_code", "recorded_at"], name="usage_recor_metric__c41032_idx"
            ),
        ),
    ]