"""Module 0002_add_profile_models."""

# Generated by Django 6.0 on 2025-12-25 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    """Migration class implementation."""

    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        help_text="Keycloak user ID", primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "session_timeout",
                    models.IntegerField(default=30, help_text="Session timeout in minutes (5-480)"),
                ),
                (
                    "notification_prefs",
                    models.JSONField(
                        default=dict,
                        help_text="Notification preferences: criticalAlerts, billingEvents, weeklyDigest, marketing",
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin Profile",
                "verbose_name_plural": "Admin Profiles",
                "db_table": "saas_admin_profile",
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "key_type",
                    models.CharField(
                        choices=[("platform", "Platform"), ("tenant", "Tenant")], max_length=10
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, help_text="For platform keys", null=True)),
                ("tenant_id", models.UUIDField(blank=True, help_text="For tenant keys", null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "key_prefix",
                    models.CharField(help_text="First 8 chars of key for display", max_length=8),
                ),
                ("key_hash", models.CharField(help_text="SHA256 hash of full key", max_length=64)),
                ("scopes", models.JSONField(default=list, help_text="List of permission scopes")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "saas_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="saas.tenant",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, default="")),
                ("primary_color", models.CharField(default="#2563eb", max_length=7)),
                ("accent_color", models.CharField(default="#3b82f6", max_length=7)),
                ("custom_domain", models.CharField(blank=True, default="", max_length=255)),
                (
                    "mfa_policy",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="optional",
                        max_length=10,
                    ),
                ),
                ("sso_enabled", models.BooleanField(default=False)),
                (
                    "sso_config",
                    models.JSONField(default=dict, help_text="SSO provider configuration"),
                ),
                (
                    "session_timeout",
                    models.IntegerField(default=30, help_text="Session timeout in minutes"),
                ),
                (
                    "feature_overrides",
                    models.JSONField(
                        default=dict, help_text="Feature overrides within tier limits"
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
                "db_table": "saas_tenant_settings",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        help_text="Keycloak user ID", primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(blank=True, default="", max_length=100)),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20)),
                (
                    "notification_prefs",
                    models.JSONField(
                        default=dict,
                        help_text="Notification preferences: agentReplies, activitySummary, productUpdates",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "saas_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(db_index=True)),
                ("device", models.CharField(max_length=200)),
                ("browser", models.CharField(blank=True, default="", max_length=100)),
                ("os", models.CharField(blank=True, default="", max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("refresh_token_hash", models.CharField(blank=True, max_length=64)),
                ("is_current", models.BooleanField(default=False)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "saas_user_session",
                "ordering": ["-last_active"],
            },
        ),
    ]