# Generated by Django 5.1.4 on 2026-01-10 00:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_add_profile_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDefault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('defaults', models.JSONField(default=dict, help_text='Canonical default settings (models, roles, quotas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Default',
                'verbose_name_plural': 'Global Defaults',
                'db_table': 'saas_global_defaults',
            },
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='auth',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='compliance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='compute',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
