groups:
  - name: feature-state
    rules:
      - alert: FeatureDisabledUnexpected
        expr: sum by(feature) (feature_state_info{state="disabled"}) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Feature disabled: {{ $labels.feature }}"
          description: "One or more features are disabled unexpectedly. Investigate configuration or upstream dependencies."

      - alert: SemanticRecallErrors
        expr: rate(semantic_recall_requests_total{result="error"}[5m]) > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Semantic recall errors occurring"
          description: "Semantic recall endpoint experiencing errors. Check vector index and embedding provider."

      - alert: EmbeddingProviderErrors
        expr: rate(embeddings_requests_total{result="error"}[5m]) > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Embedding provider errors"
          description: "Embedding requests failing. Validate API credentials, network, and provider health."
