apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    component: grafana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grafana.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.adminPassword | quote }}
          ports:
            - containerPort: 3000
