# Prod-like overrides for local development. Use with:
# docker compose -f docker-compose.yaml -f docker-compose.prod-local.yaml up -d

services:
  agent-ui:
    volumes:
      # Ensure vendor assets are served from local files to avoid CDN/mime/404
      - ./webui:/git/agent-zero/webui:ro
      - ./webui/vendor:/git/agent-zero/webui/vendor:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  gateway:
    environment:
      # For a prod-like default, require auth unless explicitly overridden in .env
      GATEWAY_REQUIRE_AUTH: ${GATEWAY_REQUIRE_AUTH:-true}
      # Ensure gateway uses local Kafka and OPA in prod-like dev
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      OPA_URL: ${OPA_URL:-http://opa:8181}
      POLICY_FAIL_OPEN: ${POLICY_FAIL_OPEN:-true}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  conversation-worker:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      OPA_URL: ${OPA_URL:-http://opa:8181}
      POLICY_FAIL_OPEN: ${POLICY_FAIL_OPEN:-true}

  tool-executor:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  memory-service:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

# Keep volumes/networks from canonical compose
