apiVersion: v1
kind: Service
metadata:
  name: telemetry-worker
  labels:
    app.kubernetes.io/name: telemetry-worker
    app.kubernetes.io/part-of: somaagent01
spec:
  selector:
    app.kubernetes.io/name: telemetry-worker
  ports:
    - name: http
      port: 8020
      targetPort: http
