apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
    component: prometheus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "prometheus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: prometheus
