version: '3.9'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: soma-kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_ENABLE_KRAFT=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  redis:
    image: redis:7-alpine
    container_name: soma-redis
    command: ["redis-server", "--save", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: soma-postgres
    environment:
      - POSTGRES_USER=soma
      - POSTGRES_PASSWORD=soma
      - POSTGRES_DB=somaagent01
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  delegation-gateway:
    image: agent-zero-dev:latest
    container_name: soma-delegation-gateway
    command: ["python3", "-m", "uvicorn", "services.delegation_gateway.main:app", "--host", "0.0.0.0", "--port", "8015"]
    environment:
      - LOG_LEVEL=INFO
      - DELEGATION_TOPIC=somastack.delegation
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - POSTGRES_DSN=postgresql://soma:soma@postgres:5432/somaagent01
    ports:
      - "8015:8015"
    volumes:
      - ./a0_data:/a0

  delegation-worker:
    image: agent-zero-dev:latest
    container_name: soma-delegation-worker
    command: ["python3", "-m", "services.delegation_worker.main"]
    environment:
      - LOG_LEVEL=INFO
      - DELEGATION_TOPIC=somastack.delegation
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./a0_data:/a0

networks:
  default:
    name: somaagent01

volumes:
  kafka_data:
  redis_data:
  postgres_data:
