# Generated by Django 5.1.4 on 2026-09-28 22:09

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_remove_capsule_legacy_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tier display name (e.g., 'Starter', 'Team', 'Enterprise')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(help_text="URL-safe identifier", unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this tier is for"),
                ),
                ("max_agents", models.IntegerField(default=1, help_text="Maximum agents allowed")),
                (
                    "max_users_per_agent",
                    models.IntegerField(default=5, help_text="Maximum users per agent"),
                ),
                (
                    "max_monthly_voice_minutes",
                    models.IntegerField(default=60, help_text="Monthly voice minutes allowance"),
                ),
                (
                    "max_monthly_api_calls",
                    models.IntegerField(default=1000, help_text="Monthly API calls allowance"),
                ),
                (
                    "max_storage_gb",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Storage allowance in GB",
                        max_digits=10,
                    ),
                ),
                (
                    "feature_defaults",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default feature configurations for this tier",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this tier can be assigned to a tenant",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Tier",
                "verbose_name_plural": "Subscription Tiers",
                "db_table": "subscription_tiers",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="subscriptio_slug_03cc71_idx"),
                    models.Index(fields=["is_active"], name="subscriptio_is_acti_a7d112_idx"),
                    models.Index(fields=["sort_order"], name="subscriptio_sort_or_3b0519_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Organization name", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for tenant", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Activation"),
                            ("churned", "Churned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "keycloak_realm",
                    models.CharField(
                        blank=True, help_text="Keycloak realm for this tenant", max_length=100
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, help_text="Primary billing contact email", max_length=254
                    ),
                ),
                (
                    "feature_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-tenant feature configuration overrides",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Arbitrary metadata for integrations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trial_ends_at",
                    models.DateTimeField(blank=True, help_text="When trial period ends", null=True),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        help_text="Current subscription tier",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="aaas.subscriptiontier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "actor_id",
                    models.UUIDField(db_index=True, help_text="User ID who performed the action"),
                ),
                (
                    "actor_email",
                    models.EmailField(
                        blank=True, help_text="Actor email (denormalized for query)", max_length=254
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action type (e.g., 'tenant.created', 'tier.updated')",
                        max_length=100,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Resource type affected (e.g., 'tenant', 'agent', 'tier')",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        blank=True, db_index=True, help_text="ID of affected resource", null=True
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="Previous state (for updates)", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="New state (for creates/updates)", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Request IP address", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="Request user agent")),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Correlation ID for request tracing",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="aaas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Agent display name", max_length=100)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier within tenant", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Agent purpose/description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Agent-specific configuration"
                    ),
                ),
                (
                    "feature_settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Feature configuration for this agent"
                    ),
                ),
                (
                    "skin_id",
                    models.UUIDField(blank=True, help_text="Associated skin/theme ID", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="aaas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "db_table": "agents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, help_text="Keycloak user ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="User email (denormalized from Keycloak)", max_length=254
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, help_text="User display name", max_length=200),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="aaas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant User",
                "verbose_name_plural": "Tenant Users",
                "db_table": "tenant_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "metric_code",
                    models.CharField(
                        db_index=True,
                        help_text="Billable metric code (e.g., 'voice_minutes', 'api_calls')",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, help_text="Usage quantity", max_digits=20
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="units", help_text="Unit of measurement", max_length=20
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context for the usage event"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When usage was recorded"
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(blank=True, help_text="Start of usage period", null=True),
                ),
                (
                    "period_end",
                    models.DateTimeField(blank=True, help_text="End of usage period", null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="aaas.agent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="aaas.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "db_table": "usage_records",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, help_text="Keycloak user ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                        ],
                        default="operator",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_users",
                        to="aaas.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent User",
                "verbose_name_plural": "Agent Users",
                "db_table": "agent_users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="agent_users_user_id_c30b77_idx"),
                    models.Index(fields=["role"], name="agent_users_role_487704_idx"),
                ],
                "unique_together": {("agent", "user_id")},
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="tenants_status_80d9b6_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["-created_at"], name="tenants_created_5c5edb_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor_id", "created_at"], name="audit_logs_actor_i_5bd818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="audit_logs_tenant__0b1a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="audit_logs_action_391715_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="audit_logs_resourc_bda8a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-created_at"], name="audit_logs_created_43fcd6_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["tenant", "status"], name="agents_tenant__fad503_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["status"], name="agents_status_f5ff61_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["-created_at"], name="agents_created_a7b1cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="agent",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["user_id"], name="tenant_user_user_id_f93ec7_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["email"], name="tenant_user_email_756120_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["role"], name="tenant_user_role_00f530_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(fields=["is_active"], name="tenant_user_is_acti_a9afac_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tenantuser",
            unique_together={("tenant", "user_id")},
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "metric_code"], name="usage_recor_tenant__b17ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "recorded_at"], name="usage_recor_tenant__d7582d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["metric_code", "recorded_at"], name="usage_recor_metric__c41032_idx"
            ),
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        help_text="Keycloak user ID", primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "session_timeout",
                    models.IntegerField(default=30, help_text="Session timeout in minutes (5-480)"),
                ),
                (
                    "notification_prefs",
                    models.JSONField(
                        default=dict,
                        help_text="Notification preferences: criticalAlerts, billingEvents, weeklyDigest, marketing",
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin Profile",
                "verbose_name_plural": "Admin Profiles",
                "db_table": "aaas_admin_profile",
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "key_type",
                    models.CharField(
                        choices=[("platform", "Platform"), ("tenant", "Tenant")], max_length=10
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, help_text="For platform keys", null=True)),
                ("tenant_id", models.UUIDField(blank=True, help_text="For tenant keys", null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "key_prefix",
                    models.CharField(help_text="First 8 chars of key for display", max_length=8),
                ),
                ("key_hash", models.CharField(help_text="SHA256 hash of full key", max_length=64)),
                ("scopes", models.JSONField(default=list, help_text="List of permission scopes")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "aaas_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        help_text="Keycloak user ID", primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(blank=True, default="", max_length=100)),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20)),
                (
                    "notification_prefs",
                    models.JSONField(
                        default=dict,
                        help_text="Notification preferences: agentReplies, activitySummary, productUpdates",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "aaas_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(db_index=True)),
                ("device", models.CharField(max_length=200)),
                ("browser", models.CharField(blank=True, default="", max_length=100)),
                ("os", models.CharField(blank=True, default="", max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("refresh_token_hash", models.CharField(blank=True, max_length=64)),
                ("is_current", models.BooleanField(default=False)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "aaas_user_session",
                "ordering": ["-last_active"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="aaas.tenant",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, default="")),
                ("primary_color", models.CharField(default="#2563eb", max_length=7)),
                ("accent_color", models.CharField(default="#3b82f6", max_length=7)),
                ("custom_domain", models.CharField(blank=True, default="", max_length=255)),
                (
                    "mfa_policy",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("optional", "Optional"),
                            ("required", "Required"),
                        ],
                        default="optional",
                        max_length=10,
                    ),
                ),
                ("sso_enabled", models.BooleanField(default=False)),
                (
                    "sso_config",
                    models.JSONField(default=dict, help_text="SSO provider configuration"),
                ),
                (
                    "session_timeout",
                    models.IntegerField(default=30, help_text="Session timeout in minutes"),
                ),
                (
                    "feature_overrides",
                    models.JSONField(
                        default=dict, help_text="Feature overrides within tier limits"
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auth", models.JSONField(blank=True, default=dict)),
                ("compliance", models.JSONField(blank=True, default=dict)),
                ("compute", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
                "db_table": "aaas_tenant_settings",
            },
        ),
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "defaults",
                    models.JSONField(
                        default=dict, help_text="Canonical default settings (models, roles, quotas)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Configuration",
                "verbose_name_plural": "Platform Configuration",
                "db_table": "aaas_platform_config",
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="capsules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Capsules defining agent identity, prompts, and capabilities (can be nested)",
                related_name="agents",
                to="core.capsule",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="primary_capsule",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary capsule for system_prompt and core identity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_agents",
                to="core.capsule",
            ),
        ),
    ]
