# Generated by Django 5.1.4 on 2026-06-12 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aaas", "0003_globaldefault_tenantsettings_auth_and_more"),
        ("core", "0007_remove_capsule_legacy_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "defaults",
                    models.JSONField(
                        default=dict, help_text="Canonical default settings (models, roles, quotas)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Configuration",
                "verbose_name_plural": "Platform Configuration",
                "db_table": "aaas_platform_config",
            },
        ),
        migrations.DeleteModel(
            name="GlobalDefault",
        ),
        migrations.RenameIndex(
            model_name="aaasfeature",
            new_name="aaas_featur_code_e72981_idx",
            old_name="aaas_featur_code_334a9a_idx",
        ),
        migrations.RenameIndex(
            model_name="aaasfeature",
            new_name="aaas_featur_categor_de001e_idx",
            old_name="aaas_featur_categor_92cec1_idx",
        ),
        migrations.RenameIndex(
            model_name="aaasfeature",
            new_name="aaas_featur_is_acti_791a93_idx",
            old_name="aaas_featur_is_acti_ed3142_idx",
        ),
        migrations.RenameIndex(
            model_name="aaasfeature",
            new_name="aaas_featur_sort_or_b84412_idx",
            old_name="aaas_featur_sort_or_e4e562_idx",
        ),
        migrations.RenameIndex(
            model_name="featureprovider",
            new_name="aaas_featur_feature_842414_idx",
            old_name="aaas_featur_feature_89e37b_idx",
        ),
        migrations.RenameIndex(
            model_name="featureprovider",
            new_name="aaas_featur_code_ade063_idx",
            old_name="aaas_featur_code_be8fe3_idx",
        ),
        migrations.RenameIndex(
            model_name="tierfeature",
            new_name="aaas_tier_f_tier_id_1665e8_idx",
            old_name="aaas_tier_f_tier_id_6c682b_idx",
        ),
        migrations.RenameIndex(
            model_name="tierfeature",
            new_name="aaas_tier_f_feature_06ee3c_idx",
            old_name="aaas_tier_f_feature_d87b80_idx",
        ),
        migrations.AddField(
            model_name="agent",
            name="capsules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Capsules defining agent identity, prompts, and capabilities (can be nested)",
                related_name="agents",
                to="core.capsule",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="primary_capsule",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary capsule for system_prompt and core identity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_agents",
                to="core.capsule",
            ),
        ),
    ]
