# Generated by Django 5.1.4 on 2026-09-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aaas", "0004_platformconfig_delete_globaldefault_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tenant",
            name="tenants_lago_cu_496f04_idx",
        ),
        migrations.RemoveIndex(
            model_name="usagerecord",
            name="usage_recor_lago_sy_da0de7_idx",
        ),
        migrations.RemoveField(
            model_name="aaasfeature",
            name="lago_billable_metric_code",
        ),
        migrations.RemoveField(
            model_name="subscriptiontier",
            name="lago_plan_code",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="lago_customer_id",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="lago_subscription_id",
        ),
        migrations.RemoveField(
            model_name="usagerecord",
            name="lago_event_id",
        ),
        migrations.RemoveField(
            model_name="usagerecord",
            name="lago_synced",
        ),
    ]
