# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x0esa01.memory.v1\"\xd5\x01\n\x0cMemoryRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06tenant\x18\x02 \x01(\t\x12\x12\n\npersona_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12<\n\x08metadata\x18\x05 \x03(\x0b\x32*.sa01.memory.v1.MemoryRecord.MetadataEntry\x12\x15\n\rcreated_at_ms\x18\x06 \x01(\x03\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc0\x01\n\x13\x43reateMemoryRequest\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x12\n\npersona_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x43\n\x08metadata\x18\x04 \x03(\x0b\x32\x31.sa01.memory.v1.CreateMemoryRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x14\x43reateMemoryResponse\x12,\n\x06record\x18\x01 \x01(\x0b\x32\x1c.sa01.memory.v1.MemoryRecord\"\x1e\n\x10GetMemoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\"A\n\x11GetMemoryResponse\x12,\n\x06record\x18\x01 \x01(\x0b\x32\x1c.sa01.memory.v1.MemoryRecord\"H\n\x13ListMemoriesRequest\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x12\n\npersona_id\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"E\n\x14ListMemoriesResponse\x12-\n\x07records\x18\x01 \x03(\x0b\x32\x1c.sa01.memory.v1.MemoryRecord2\x97\x02\n\rMemoryService\x12Y\n\x0c\x43reateMemory\x12#.sa01.memory.v1.CreateMemoryRequest\x1a$.sa01.memory.v1.CreateMemoryResponse\x12P\n\tGetMemory\x12 .sa01.memory.v1.GetMemoryRequest\x1a!.sa01.memory.v1.GetMemoryResponse\x12Y\n\x0cListMemories\x12#.sa01.memory.v1.ListMemoriesRequest\x1a$.sa01.memory.v1.ListMemoriesResponseB Z\x1egithub.com/soma/sa01/memory/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/soma/sa01/memory/v1'
  _globals['_MEMORYRECORD_METADATAENTRY']._loaded_options = None
  _globals['_MEMORYRECORD_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CREATEMEMORYREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CREATEMEMORYREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_MEMORYRECORD']._serialized_start=33
  _globals['_MEMORYRECORD']._serialized_end=246
  _globals['_MEMORYRECORD_METADATAENTRY']._serialized_start=199
  _globals['_MEMORYRECORD_METADATAENTRY']._serialized_end=246
  _globals['_CREATEMEMORYREQUEST']._serialized_start=249
  _globals['_CREATEMEMORYREQUEST']._serialized_end=441
  _globals['_CREATEMEMORYREQUEST_METADATAENTRY']._serialized_start=199
  _globals['_CREATEMEMORYREQUEST_METADATAENTRY']._serialized_end=246
  _globals['_CREATEMEMORYRESPONSE']._serialized_start=443
  _globals['_CREATEMEMORYRESPONSE']._serialized_end=511
  _globals['_GETMEMORYREQUEST']._serialized_start=513
  _globals['_GETMEMORYREQUEST']._serialized_end=543
  _globals['_GETMEMORYRESPONSE']._serialized_start=545
  _globals['_GETMEMORYRESPONSE']._serialized_end=610
  _globals['_LISTMEMORIESREQUEST']._serialized_start=612
  _globals['_LISTMEMORIESREQUEST']._serialized_end=684
  _globals['_LISTMEMORIESRESPONSE']._serialized_start=686
  _globals['_LISTMEMORIESRESPONSE']._serialized_end=755
  _globals['_MEMORYSERVICE']._serialized_start=758
  _globals['_MEMORYSERVICE']._serialized_end=1037
# @@protoc_insertion_point(module_scope)
