"""Module 0001_zero_data_loss_infrastructure."""

# Generated by Django 5.1.4 on 2025-12-24 20:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class implementation."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("resource_type", models.CharField(db_index=True, max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=255, null=True)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "agent_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("schema", models.JSONField(default=dict)),
                ("config", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "capabilities",
                "db_table": "capabilities",
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("rollout_percentage", models.IntegerField(default=0)),
                ("tenant_overrides", models.JSONField(default=dict)),
                ("user_overrides", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "feature_flags",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("job_type", models.CharField(db_index=True, max_length=100)),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "jobs",
                "ordering": ["-priority", "scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("persona_id", models.CharField(blank=True, max_length=255, null=True)),
                ("tenant", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("agent_id", models.CharField(db_index=True, max_length=255)),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("value", models.JSONField()),
                ("is_secret", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agent_settings",
                "unique_together": {("agent_id", "key")},
            },
        ),
        migrations.CreateModel(
            name="Capsule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("schema", models.JSONField(default=dict)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "capsules",
                "unique_together": {("name", "version", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="CapsuleInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("state", models.JSONField(default=dict)),
                ("status", models.CharField(db_index=True, default="running", max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.capsule",
                    ),
                ),
            ],
            options={
                "db_table": "capsule_instances",
            },
        ),
        migrations.CreateModel(
            name="DeadLetterMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_outbox_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("original_topic", models.CharField(db_index=True, max_length=255)),
                ("idempotency_key", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField()),
                ("error_type", models.CharField(blank=True, max_length=255, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("original_created_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, max_length=255, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "dead_letter_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["original_topic", "resolved"], name="dead_letter_origina_0dfe3a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("operation_type", models.CharField(db_index=True, max_length=100)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "idempotency_records",
                "indexes": [
                    models.Index(fields=["expires_at"], name="idempotency_expires_79c374_idx"),
                    models.Index(
                        fields=["operation_type", "created_at"],
                        name="idempotency_operati_5c7c89_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MemoryReplica",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("persona_id", models.CharField(blank=True, max_length=255, null=True)),
                ("tenant", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("coord", models.CharField(blank=True, max_length=255, null=True)),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="The core memory content payload"),
                ),
                (
                    "wal_timestamp",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        help_text="Original WAL event timestamp",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Memory Replica",
                "verbose_name_plural": "Memory Replicas",
                "db_table": "memory_replica",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "session_id"], name="memory_repl_tenant_871ef9_idx"
                    ),
                    models.Index(fields=["wal_timestamp"], name="memory_repl_wal_tim_200047_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("topic", models.CharField(db_index=True, max_length=255)),
                ("partition_key", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("next_retry_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("dead", "Dead Letter"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "outbox_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="outbox_mess_status_74979f_idx"
                    ),
                    models.Index(fields=["topic", "status"], name="outbox_mess_topic_7a24c9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PendingMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("namespace", models.CharField(default="wm", max_length=100)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("synced", models.BooleanField(db_index=True, default=False)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pending_memories",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["synced", "created_at"], name="pending_mem_synced_628f0d_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "synced"], name="pending_mem_tenant__7f8f45_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("template", models.TextField()),
                ("variables", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prompts",
                "unique_together": {("name", "version", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="SessionEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("role", models.CharField(default="user", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "session_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UISetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("value", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ui_settings",
                "unique_together": {("tenant", "user_id", "key")},
            },
        ),
    ]
