# Generated by Django 6.0 on 2025-12-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_zero_data_loss_infrastructure"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorOutbox",
            fields=[
                ("event_id", models.CharField(max_length=36, primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("tenant_id", models.CharField(db_index=True, max_length=36)),
                ("agent_id", models.CharField(db_index=True, max_length=36)),
                ("user_id", models.CharField(blank=True, default="", max_length=36)),
                ("session_id", models.CharField(blank=True, default="", max_length=36)),
                ("target_service", models.CharField(db_index=True, max_length=50)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("synced", models.BooleanField(db_index=True, default=False)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("dead_letter", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "sensor_outbox",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["synced", "target_service", "created_at"],
                        name="sensor_outb_synced_aa93a2_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "event_type"], name="sensor_outb_tenant__9bbefe_idx"
                    ),
                    models.Index(
                        fields=["dead_letter", "created_at"], name="sensor_outb_dead_le_240654_idx"
                    ),
                ],
            },
        ),
    ]
