"""Module 0003_infrastructure_models."""

# Generated by Django 6.0 on 2025-12-25 15:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    """Migration class implementation."""

    dependencies = [
        ("core", "0002_sensor_outbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Rate limit key (e.g., 'api_calls', 'llm_tokens')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of this rate limit"
                    ),
                ),
                (
                    "limit",
                    models.BigIntegerField(
                        default=1000, help_text="Maximum requests/tokens/etc allowed in window"
                    ),
                ),
                (
                    "window_seconds",
                    models.IntegerField(
                        default=3600,
                        help_text="Time window in seconds (e.g., 3600 for 1 hour, 86400 for 24 hours)",
                    ),
                ),
                (
                    "policy",
                    models.CharField(
                        choices=[
                            ("HARD", "Hard limit - block when exceeded"),
                            ("SOFT", "Soft limit - warn but allow"),
                            ("NONE", "No enforcement - logging only"),
                        ],
                        default="HARD",
                        help_text="What happens when limit is exceeded",
                        max_length=10,
                    ),
                ),
                (
                    "tier_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-tier limit overrides (tier_slug -> limit)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether this rate limit is enforced"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, help_text="User who created this", max_length=255),
                ),
                (
                    "updated_by",
                    models.CharField(blank=True, help_text="User who last updated", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Rate Limit Policy",
                "verbose_name_plural": "Rate Limit Policies",
                "db_table": "rate_limit_policies",
                "ordering": ["key"],
                "indexes": [
                    models.Index(fields=["key"], name="rate_limit__key_975cd2_idx"),
                    models.Index(fields=["is_active"], name="rate_limit__is_acti_48cdfb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        db_index=True,
                        help_text="Service name (e.g., 'postgresql', 'redis', 'temporal')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Human-readable service name", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="core",
                        help_text="Service category (core, external, infrastructure)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Current health status",
                        max_length=20,
                    ),
                ),
                (
                    "latency_ms",
                    models.FloatField(
                        blank=True, help_text="Last measured latency in milliseconds", null=True
                    ),
                ),
                (
                    "last_check",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the last health check was performed",
                    ),
                ),
                (
                    "last_healthy",
                    models.DateTimeField(
                        blank=True, help_text="When the service was last healthy", null=True
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional service-specific details (version, connections, etc.)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if status is not healthy"
                    ),
                ),
                (
                    "check_url",
                    models.CharField(
                        blank=True, help_text="Health check endpoint URL", max_length=500
                    ),
                ),
                (
                    "check_interval_seconds",
                    models.IntegerField(default=30, help_text="How often to check this service"),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this service is critical for platform operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Health",
                "verbose_name_plural": "Service Health Records",
                "db_table": "service_health",
                "ordering": ["category", "service_name"],
                "indexes": [
                    models.Index(fields=["service_name"], name="service_hea_service_12460b_idx"),
                    models.Index(fields=["status"], name="service_hea_status_eaccf8_idx"),
                    models.Index(fields=["category"], name="service_hea_categor_142117_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InfrastructureConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Configuration key (e.g., 'host', 'port', 'pool_size')",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="Configuration value (encrypted if is_secret)"
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False, help_text="Whether this value should be encrypted/hidden"
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True, help_text="Whether this can be edited through UI"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this configuration option"
                    ),
                ),
                (
                    "default_value",
                    models.TextField(blank=True, help_text="Default value for this configuration"),
                ),
                (
                    "value_type",
                    models.CharField(
                        default="string",
                        help_text="Value type: string, integer, boolean, url, json",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Associated service",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="core.servicehealth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infrastructure Config",
                "verbose_name_plural": "Infrastructure Configs",
                "db_table": "infrastructure_configs",
                "ordering": ["service", "key"],
                "unique_together": {("service", "key")},
            },
        ),
    ]