"""Module 0004_capsule_capabilities_whitelist_and_more."""

# Generated by Django 5.1.4 on 2026-01-03 12:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class implementation."""

    dependencies = [
        ("core", "0003_infrastructure_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="capsule",
            name="capabilities_whitelist",
            field=models.JSONField(default=list, help_text="List of allowed Tool IDs"),
        ),
        migrations.AddField(
            model_name="capsule",
            name="neuromodulator_baseline",
            field=models.JSONField(
                default=dict, help_text="Baseline chemical state (Dopamine, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="personality_traits",
            field=models.JSONField(default=dict, help_text="Big 5 Traits (Openness, etc.) 0.0-1.0"),
        ),
        migrations.AddField(
            model_name="capsule",
            name="registry_signature",
            field=models.TextField(
                blank=True, help_text="Ed25519 Signature from Registry Authority", null=True
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="resource_limits",
            field=models.JSONField(default=dict, help_text="Max wall clock, concurrency, etc."),
        ),
        migrations.AddField(
            model_name="capsule",
            name="system_prompt",
            field=models.TextField(default="", help_text="Base cognitive instruction set"),
        ),
        migrations.AlterField(
            model_name="capsule",
            name="config",
            field=models.JSONField(default=dict, help_text="Legacy: Configuration"),
        ),
        migrations.AlterField(
            model_name="capsule",
            name="schema",
            field=models.JSONField(default=dict, help_text="Legacy: Tool schemas"),
        ),
        migrations.CreateModel(
            name="Constitution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="Semantic Version (e.g., 1.0.0)", max_length=50),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 Hash of normalized content", max_length=64, unique=True
                    ),
                ),
                ("signature", models.TextField(help_text="Ed25519 Signature of the content_hash")),
                ("content", models.JSONField(help_text="The ")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Only one can be active at a time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "constitutions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active"], name="constitutio_is_acti_3b6f83_idx"),
                    models.Index(fields=["content_hash"], name="constitutio_content_431263_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="capsule",
            name="constitution",
            field=models.ForeignKey(
                help_text="The binding legal framework",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capsules",
                to="core.constitution",
            ),
        ),
    ]
