# Generated by Django 5.1.4 on 2026-01-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_capsule_capabilities_whitelist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capsule",
            name="certified_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of certification", null=True
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="constitution_ref",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cross-system reference: {'checksum': str, 'url': str}",
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent capsule this was cloned from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.capsule",
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")],
                db_index=True,
                default="draft",
                help_text="Lifecycle state: draft, active, archived",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="capsule",
            index=models.Index(fields=["tenant", "status"], name="capsules_tenant_ad8b89_idx"),
        ),
        migrations.AddIndex(
            model_name="capsule",
            index=models.Index(
                fields=["tenant", "name", "version"], name="capsules_tenant_f732a0_idx"
            ),
        ),
    ]
