# Generated by Django 5.1.4 on 2026-06-12 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils.text import slugify


def map_capsule_tenants_to_fk(apps, schema_editor):
    """Map legacy Capsule.tenant string values to aaas.Tenant rows.

    Runs before Capsule.tenant is altered from CharField to ForeignKey.
    """
    Tenant = apps.get_model("aaas", "Tenant")
    SubscriptionTier = apps.get_model("aaas", "SubscriptionTier")
    Capsule = apps.get_model("core", "Capsule")

    fallback_tier, _ = SubscriptionTier.objects.get_or_create(
        slug="default",
        defaults={
            "name": "Default Tier",
            "is_active": True,
            "is_public": False,
            "sort_order": 0,
        },
    )

    fallback_tenant, _ = Tenant.objects.get_or_create(
        slug="default",
        defaults={
            "name": "Default Tenant",
            "tier": fallback_tier,
            "status": "active",
        },
    )

    def _tenant_for_value(value):
        value = (value or "").strip()
        if not value:
            return fallback_tenant

        try:
            tenant_uuid = uuid.UUID(value)
            return Tenant.objects.get(id=tenant_uuid)
        except (ValueError, Tenant.DoesNotExist):
            pass

        base_slug = slugify(value) or "tenant"
        slug = base_slug
        counter = 1
        while True:
            tenant, created = Tenant.objects.get_or_create(
                slug=slug,
                defaults={
                    "name": value,
                    "tier": fallback_tier,
                    "status": "active",
                },
            )
            if created or tenant.name == value:
                return tenant
            slug = f"{base_slug}-{counter}"
            counter += 1

    for capsule in Capsule.objects.all().iterator():
        tenant = _tenant_for_value(capsule.tenant)
        capsule.tenant = str(tenant.id)
        capsule.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ("aaas", "0004_platformconfig_delete_globaldefault_and_more"),
        ("core", "0007_remove_capsule_legacy_fields"),
        (
            "llm",
            "0003_rename_llm_model_c_is_acti_routing_idx_llm_model_c_is_acti_1e0095_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(default="", max_length=255)),
                ("asset_type", models.CharField(db_index=True, max_length=50)),
                ("format", models.CharField(max_length=50)),
                ("content", models.BinaryField(blank=True, null=True)),
                ("content_size_bytes", models.BigIntegerField(default=0)),
                ("dimensions", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=255, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("tombstone_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DelegationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("task_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="received", max_length=50)),
                ("callback_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "delegation_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("plan_id", models.CharField(db_index=True, max_length=255)),
                ("step_index", models.IntegerField(default=0)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("provider_name", models.CharField(max_length=255)),
                ("provider_id", models.CharField(max_length=255)),
                ("attempt_number", models.IntegerField(default=1)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("asset_id", models.CharField(blank=True, max_length=255, null=True)),
                ("latency_ms", models.FloatField(default=0.0)),
                ("cost_estimate_cents", models.IntegerField(blank=True, null=True)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("quality_feedback", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "execution_records",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(db_index=True, max_length=100)),
                ("deployment_mode", models.CharField(default="standard", max_length=50)),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "model_profiles",
                "ordering": ["role"],
            },
        ),
        migrations.CreateModel(
            name="MultimodalOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("task_id", models.CharField(db_index=True, max_length=255)),
                ("step_type", models.CharField(db_index=True, max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("result", models.JSONField(default=dict)),
                ("provider", models.CharField(default="", max_length=100)),
                ("success", models.BooleanField(default=False)),
                ("latency_ms", models.FloatField(default=0.0)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("cost_cents", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "multimodal_outcomes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Provenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("asset_id", models.CharField(db_index=True, max_length=255)),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("operation", models.CharField(blank=True, max_length=100, null=True)),
                ("generation_params", models.JSONField(blank=True, default=dict)),
                ("rework_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "provenance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.RenameIndex(
            model_name="capsule",
            new_name="capsules_tenant__fb8024_idx",
            old_name="capsules_tenant_ad8b89_idx",
        ),
        migrations.RenameIndex(
            model_name="capsule",
            new_name="capsules_tenant__585481_idx",
            old_name="capsules_tenant_f732a0_idx",
        ),
        migrations.AddField(
            model_name="capsule",
            name="browser_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Web browsing and vision model (e.g. perplexity)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capabilities_browser",
                to="llm.llmmodelconfig",
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Active tools/MCP servers available to this agent",
                related_name="capsules",
                to="core.capability",
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="chat_model",
            field=models.ForeignKey(
                help_text="The main cognitive engine (e.g. gpt-4-turbo)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capabilities_chat",
                to="llm.llmmodelconfig",
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="image_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Image generation model (e.g. dall-e-3)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capabilities_image",
                to="llm.llmmodelconfig",
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="learning_config",
            field=models.JSONField(
                default=dict,
                help_text="GMD Hyperparameters (eta, lambda, alpha) & Reward Thresholds",
            ),
        ),
        migrations.AddField(
            model_name="capsule",
            name="voice_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Voice synthesis model (e.g. elevenlabs-v1)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capabilities_voice",
                to="llm.llmmodelconfig",
            ),
        ),
        migrations.AlterField(
            model_name="capability",
            name="implementation",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Tool implementation mapping: {\n            "type": "python",\n            "module": "tools.echo",\n            "class": "EchoTool"\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="capability",
            name="policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Tool execution policy: {\n            "requires_approval": false,\n            "timeout_seconds": 30,\n            "max_retries": 3\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="capsule",
            name="memory_pointer",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Memory namespace pointer: {\n            "tenant": "acme_corp",\n            "namespace": "agent_xxx_chat_history",\n            "recall_limit": 10,\n            "similarity_threshold": 0.7\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="capsule",
            name="neuromodulator_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Last-synced neuromodulator state from SomaBrain: {\n            "dopamine": 0.5, "serotonin": 0.6,\n            "norepinephrine": 0.4, "acetylcholine": 0.5,\n            "last_synced_at": "2026-05-21T13:00:00Z"\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="capsule",
            name="persona_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Agent persona configuration: {\n            "knobs": {"intelligence_level": 5, "autonomy_level": 5, "resource_budget": 0.10},\n            "prompts": {"injection_prompts": [...], "tool_prompts": {...}},\n            "memory": {"recall_limit": 10, "similarity_threshold": 0.7},\n            "learned": {"lane_preferences": {...}}\n        }\n        ',
            ),
        ),
        migrations.RunPython(
            map_capsule_tenants_to_fk,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="capsule",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capsules",
                to="aaas.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="capsule",
            name="tool_policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Tool execution policy: {\n            "auto_execute": ["echo", "timestamp"],\n            "approval_required": ["code_execute"],\n            "denied": ["file_delete"]\n        }\n        ',
            ),
        ),
        migrations.AddIndex(
            model_name="executionrecord",
            index=models.Index(
                fields=["plan_id", "step_index", "-started_at"],
                name="execution_r_plan_id_0690bc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modelprofile",
            unique_together={("role", "deployment_mode")},
        ),
    ]
