apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
    - name: peer
      port: {{ .Values.service.peerPort }}
      targetPort: peer
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}