apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "etcd.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "etcd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "etcd.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: etcd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: client
              containerPort: {{ .Values.service.port }}
            - name: peer
              containerPort: {{ .Values.service.peerPort }}
          env:
            - name: ETCD_NAME
              value: "{{ include "etcd.fullname" . }}"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: 'http://{{ include "etcd.fullname" . }}:{{ .Values.service.port }}'
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: 'http://{{ include "etcd.fullname" . }}:{{ .Values.service.peerPort }}'
            - name: ETCD_INITIAL_CLUSTER
              value: '{{ include "etcd.fullname" . }}=http://{{ include "etcd.fullname" . }}:{{ .Values.service.peerPort }}'
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
            - name: ETCD_LISTEN_PEER_URLS
              value: 'http://0.0.0.0:{{ .Values.service.peerPort }}'
            - name: ETCD_LISTEN_CLIENT_URLS
              value: 'http://0.0.0.0:{{ .Values.service.port }}'
          volumeMounts:
            - name: data
              mountPath: /etcd-data
      {{- if not .Values.persistence.enabled }}
      # Use an ephemeral emptyDir volume when persistence is disabled (local/Kind)
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
    {{- end }}