apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "etcd.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "etcd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "etcd.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: etcd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: client
              containerPort: {{ .Values.service.port }}
            - name: peer
              containerPort: {{ .Values.service.peerPort }}
          env:
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: {{ printf "http://%s:%d" (include "etcd.fullname" .) (int .Values.service.port) | quote }}
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: {{ printf "http://%s:%d" (include "etcd.fullname" .) (int .Values.service.peerPort) | quote }}
            - name: ETCD_INITIAL_CLUSTER
              value: {{ printf "default=http://%s:%d" (include "etcd.fullname" .) (int .Values.service.peerPort) | quote }}
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
          volumeMounts:
            - name: data
              mountPath: /etcd-data
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
