// Enhanced component import system wii18n.t('ui_i18n_t_ui_error_handling_js')dling, and performance
import { emit, on } from "i18n.t('ui_i18ni18n.t('ui_returi18n.t('ui_return_type_i18n_t_ui_component_error_l')rror, createErrorBoundary } from "i18n.ti18n.t('ui_i18n_t')8n_t_i18n.t('ui_div_clai18n.t('ui_component_error')rordata_usermessage_mponent_error_boundary_h3_component_ei18n.t('ui_i18n_t_ui_advanced_cache_with_metadata_and_versioning_const_componentcache_new_map_const_cachestats_hits_0_misses_0_errors_0_lastcleanup_date_now_enhanced_lock_system_with_timeout_and_metadai18n_t_ui_return_type_error_html_ktimeouts_new_map_component_loading_confi18n_t_ui_component_error_config_ci18n_t_ui_errordata_usermessage_0_5_minutes_cachemaxsize_100_locktimeout_30i18n_t_ui_reload_page_seconds_retryattemi18n_t_ui_advanced_cache_with_metadata_and_versioning_const_componentcache_new_map_const_cachestats_hits_0_misses_0_errors_0_lastcleanup_date_now_enhanced_lock_system_with_timeout_and_metadata_const_importlocks_new_map_const_locktimeouts_new_map_component_loading_configuration_const_config_cachemaxage_5_60_1000_5_minutes_cachemaxsize_100_locktimeout_30000_30_seconds_retryattempts_2_retrydelay_1000_enabledebug_false_enablepreloading_true_enhanced_cache_management_utilities_function_cleanupcache_const_now_date_now_if_now_cachestats_lastcleanup_componentcache_delete_url_cachestats_lastcleanup_now_function_getfromcache_url_const_cached_i18n_t_ui_config_cachemaxage_componentcache_delete_url_if_componentcache_size_config_cachemaxsize_const_entries_array_from_componentcache_entries_sort_a_b_a_1_timestamp_b_1_timestamp_const_toremove_entries_slice_0_entries_length_config_cachemaxsize_toremove_foreach_url_componentcache_delete_url_cachestats_lastcleanup_now_function_getfromcache_url_const_cached_componentcache_get_url_if_cached_date_now_cached_timestamp_nced_lock_management_with_timeout_function_acquirelock_lockkey_if_importlocks_has_lockkey_if_config_enabledebug_console_log_component_already_loading_for_lockkey_return_false_importlocks_set_lockkey_date_now_set_up_timeout_for_lock_release_const_timeoutid_settimeout_if_importlocks_has_lockkey_console_warn_lock_timeout_for_lockkey_releaselock_lockkey_config_locktimeout_locktimeouts_set_lockkey_timeoutid_return_true_function_releaselock_lockkey_importlocks_delete_lockkey_const_timeoutid_locktimeouts_get_lockkey_if_timeoutid_cleartimeout_timeoutid_locktimeouts_delete_lockkey_export_const_importcomponent_componenterrorboundi18n_t_ui_if_importlocks_has_lockkey_console_warn_lock_timeout_for_lockkey_releaselock_lockkey_config_locktimeout_locktimeouts_set_lockkey_timeoutid_return_true_function_releaselock_lockkey_importlocks_delete_lockkey_const_timeoutid_locktimeouts_get_lockkey_if_timeoutid_cleartimeout_timeoutid_locktimeouts_delete_lockkey_export_const_importcomponent_componenterrorboundary_wrapasync_async_function_path_targetelement_create_a_unique_key_for_this_import_based_on_the_target_element_const_lockkey_targetelement_id_targetelement_getattribute_data_component_id_anonymous_path_if_this_component_is_already_being_loaded_return_early_if_acquirelock_lockkey_if_config_enabledebug_console_log_component_path_is_already_being_loaded_for_target_targetelement_return_const_starttime_date_now_let_attempt_0_try_if_targetelement_throw_new_error_target_element_is_required_show_enhanced_loading_indicator_with_path_info_targetelement_innerhtml_let_lasterror_for_attempt_0_attempt_icator_with_path_info_targetelement_innerhtml_let_lasterror_for_attempt_0_attempt')ror_for_attempt_0_attempt_config_retryattempts_attempt_i18n_t_ui_loading_path_nst_response_await_feti18n_t_ui_full_component_url_with_error_handling_const_componenturl_path_startswith_path_slice_1_components_path_get_html_from_cache_or_fetch_with_retry_logic_let_html_getfromcache_componenturl_if_html_let_lasterror_for_attempt_0_attempt_tp_response_status_loading_component_path_response_statustext_errortext')onent_path_response_statustext_errortext_html_await_response_text_validate_html_content_if_html_html_trim_length_0_throw_new_error_empty_content_received_for_component_path_store_in_cache_with_metadata_setii18n.t('ui_empty_content_received_for_component_path')asterror_error_cachestats_errors_i18n_t')t_path_after_config_retryattempts_1_attempts_parse_html_with_error_handling_let_doc_try_const_parser_new_domparser_doc_parser_parsefromstring_html_i18n_t_ui_text_hi18n_t_ui_settimeout_resolve_config_retrydelay_attempt_1_if_html_throw_lasterror_new_error_failed_to_load_component_path_after_config_retryattempts_1_attempts_parse_html_with_error_handling_let_doc_try_const_parser_new_domparser_doc_parser_parsefromstring_html_text_html_check_for_parsing_errors_const_parsererror_doc_queryselector_parsererror_if_parsererror_throw_new_error_html_parsing_error_in_component_path_parsererror_textcontent_catch_parseerror_throw_new_error_failed_to_parse_html_for_component_path_parseerror_message_process_all_nodes_with_enhanced_error_handling_and_tracking_const_allnodes_doc_queryselectorall_style_doc_queryselectorall_script_doc_body_childnodes_filter_node_node_node_nodetype_1_only_element_nodes_const_loadpromises_const_loadedresources_new_set_let_blobcounter_0_for_const_node_of_allnodes_try_if_node_nodename_script_const_ismodule_node_type_module_node_getattribute_type_module_if_ismodule_if_node_src_for_esolvedurl_const_modulepromise_import_resolvedurl_catch_err_console_error_failed_to_load_module_resolvedurl_err_emit_component_error_type_module_url_resolvedurl_error_err_message_throw_err_loadpromises_push_modi18n_t_ui_console_error_failed_to_load_module_resolvedurl_err_emit_component_error_type_module_url_resolvedurl_error_err_message_throw_err_loadpromises_push_modulepromise_else_handle_inline_module_scripts_const_virtualurl_componenturl_replace_g_blobcounter_js_if_loadedresources_has_virtualurl_loadedresources_add_virtualurl_transform_relative_import_paths_to_absolute_urls_with_enhanced_regex_let_content_node_textcontent_replace_import_s_s_from_s_g_match_bindings_importpath_convert_relative_or_root_based_e_g_src_to_absolute_urls_if_https_test_importpath_const_absoluteurl_new_url_importpath_globalthis_location_origin_href_return_import_bindings_from_absoluteurl_return_match_add_sourceurl_for_debugging_and_error_tracking_content_n_sourceurl_virtualurl_create_a_blob_from_the_rewritten_content_const_blob_new_blob_content_type_text_javascript_const_bloburl_url_createobjecturl_blob_const_modulepromise_import_bloburl_catch_err_console_error_failed_to_load_inline_module_virtualurl_err_emit_component_error_type_inline_module_url_virtualurl_error_err_message_throw_err_finally_clean_up_blob_url_to_prevent_memory_leaks_settimeout_url_revokeobjecturl_bloburl_1000_loadpromises_push_modulepromise_else_non_module_script_with_enhanced_handling_const_script_document_createelement_script_copy_all_attributes_with_filtering_array_from_node_attributes_foreach_attr_if_attr_name_type_attr_value_module_script_setattribute_attr_name_attr_value_script_textcontent_node_textcontent_if_script_src_const_promise_new_promise_resolve_reject_script_onload_emit_component_loaded_type_script_src_script_src_resolve_script_onerror_const_error_new_error_failed_to_load_script_script_src_emit_component_error_type_script_src_script_src_error_error_message_reject_error_loadpromises_push_promise_targetelement_appendchild_script_else_if_node_nodename_style_node_nodename_link_node_rel_stylesheet_enhanced_style_link_handling_const_clone_node_clonenode_true_if_clone_tagname_link_clone_rel_stylesheet_const_promise_new_promise_resolve_reject_clone_onload_emit_component_loaded_type_stylesheet_href_clone_href_resolve_clone_onerror_const_error_new_error_failed_to_load_stylesheet_clone_href_emit_component_error_type_stylesheet_href_clone_href_error_error_message_reject_error_loadpromises_push_promise_targetelement_appendchild_clone_else_enhanced_dom_node_cloning_with_error_handling_try_const_clone_node_clonenode_true_targetelement_appendchild_clone_catch_cloneerror_console_warn_failed_to_clone_node_node_nodename_cloneerror_emit_component_warning_type_clone_error_nodename_node_nodename_error_cloneerror_message_catch_nodeerror_console_error_error_processing_node_node_nodename_nodeerror_emit_component_error_type_node_processing_nodename_node_nodename_error_nodeerror_message_wait_for_all_tracked_external_scripts_styles_to_finish_loading_with_enhanced_error_handling_try_await_promise_all_loadpromises_catch_loaderror_console_error_error_loading_resources_for_component_path_loaderror_throw_new_error_component_resource_loading_failed_loaderror_message_remove_loading_indicator_with_enhanced_cleanup_const_loadingel_targetelement_queryselector_scope_loading_if_loadingel_loadingel_remove_load_any_nested_components_with_error_handling_try_await_loadcomponents_targetelement_catch_nestederror_console_warn_error_loading_nested_components_for_path_nestederror_emit_component_warning_type_nested_components_path_error_nestederror_message_emit_component_loaded_event_const_loadtime_date_now_starttime_emit_component_loaded_type_component_path_loadtime_attempt_attempt_1_cachehit_getfromcache_componenturl_null_if_config_enabledebug_console_log_component_path_loaded_in_loadtime_ms_return_parsed_document_return_doc_catch_error_enhanced_error_handling_with_the_new_system_await_handleerror_error_component_componentsystem_function_importcomponent_path_targetelementid_targetelement_id_unknown_lockkey_show_error_in_ui_targetelement_innerhtml_18n_t_ui_error_actions')">
          <ii18n.t('ui_error_message')class="i18n.t('ui_i18n_t_ui_i18n_t_ui_errori18n.t('ui_18n_t_ui_error_actions')t('ui_i18n_t_ui_i18n_t_uii18n.t('ui_error_message')component_path_thi18n.t('ui_i18n_t_ui_error_retry')lement_parentelement'i18n.t('ui_i18n_t_ui_error_message_tcomponent_path_this_parentelement_parentelement_parentelement')" i18n.t('ui_retry')ck="i18n.t('ui_i18n_t_ui_i18n_t_i18n.t('ui_i18n_t_ui_error_refresh')etry_eload')i18n.t('ui_retry') Page</button>i18n.t('ui_i18n_t_ui_i18n.t('ui_retry')w_locati18n_t_ui_retry_eload')('ui_reload_page')errori18n.t('ui_reload_page')ly {
    // Release the li18n.t('ui_reload_page') regardless of i18n.t('ui_ri18n.t('ui_reload_page'))lure
    releaseLock(lockKey);
  }
});

// Load all x-component tags starting from root elements
export async function loadComponents(roots = [document.documentElement]) {
  try {
    // Convert single root to array if needed
    const rootElements = Array.isArray(roots) ? roots : [roots];

    // Find all top-level components and load them in parallel
    const components = rootElements.flatMap((root) =>
      Array.from(root.querySelectorAll("i18n.t('ui_i18n_t_ui_i18n_t_ui_x_component')"))
    );

    if (components.leni18n.t('ui_i18n_t_ui_x_component')await Promise.all(
      components.map(async (component) => {   
        const path = component.getAttribute("i18n.t('ui_i18n_t_ui_i18n_t_ui_path')");
        if (!path) {
      i18n.t('ui_i18n_t_ui_path')("i18n.t('ui_i18n_t_ui_i18n_t_ui_x_component_missing_path_ati18n.t('ui_i18n_t_ui_x_component_missing_path_attribute')   }
        await importComponent(path, component);
      })
    );
  } catch (error) {
    console.error("i18n.t('ui_i18n_t_ui_i18n_t_ui_error_loading_comi18n.t('ui_i18n_t_ui_error_loading_components')n to traverse parents and collect x-component attributes
export function getParentAttributes(el) {
  let element = el;
  let attrs = {};

  while (element) {
    if (element.tagName.toLowerCase() === 'x-component') {
      // Get ai18n.t('ui_x_component')es
      for (let attr of element.attributes) {
        try {
          // Try to parse as JSON first
          attrs[attr.name] = JSON.parse(attr.value);
        } catch(_e) {
          // If not JSON, use raw value
          attrs[attr.name] = attr.value;
        }
      }
    }
    element = element.parentElement;
  }
  return attrs;
}
// expose as global for x-components in Alpine
globalThis.xAttrs = getParentAttributes;

// Initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEveni18n.t('ui_loading')er('DOMContentLoaded', () => loadCi18n.t('ui_domcontentloaded')else {
  loadComponents();
}

// Watch for DOM changes to dynamically load x-components
const observer = new MutationObserver((mutations) => {
  for (const mutation of mutations) {
    for (const node of mutation.addedNodes) {
      if (node.nodeType === 1) {
        // ELEMENT_NODE
        // Check if this node or its descendants contain x-component(s)
        if (node.matches?.("i18n.t('ui_i18n_t_ui_i18n_t_ui_x_compoi18n.t('ui_i18n_t_ui_x_component')portComponent(node.getAttribute("i18n.t('ui_i18n_t_ui_i18n_t_i18n.t('ui_i18n_t_ui_path'));
        } else if (node.querySelectorAll) {
          loadComponents([node]);
        }
      }
    }
  }
});
observer.i18n.t('ui_i18n_t_ui_event_bus_js')childList: true, subtree: true });
