import { getContext } from "i18n.t('ui_i18n_t_ui_i18n_t_uii18n.t('ui_i18n_t_ui_i18n_t_ui_index_js') async function openHistoryModal() {
    try {
        const hist = await window.sendJsonData("i18n.t('ui_i18n_t_uii18n.t('ui_i18n_t_ui_i18n_t_ui_history_get')", { context: getCi18n.t('uii18n.t('ui_i18n_t_ui_index_js')// const data = JSON.stringify(hist.history, null, 4);
        const data = hist.history
        const size = hist.i18n.t('uii18n.t('ui_i18n_t_ui_history_get')wEditorModal(data, "i18n.t('uii18n.t('ui_i18n_t_ui_i18n_t_ui_markdown')markdown')", `History ~${size} tokens`, "i18n.t('ui_i18n_t_ui_i18n_t_ui_conversation_history_visible_to_the_llm_history_is_compressed_to_fit_into_the_contexti18n_t')the_contexti18n_t_ui_i1i18n.t('ui_catch_e_window_toastfii18n.t('ui_history_size_tokens')ation_history_visible_to_the_llm_history_is_compressed_to_fit_into_the_context_window_over_time_chat_i18n.t('ui_chat_histi18n_t')ory_size_tokens_return_ei18n.t('ui_return_export_async_functi18n_t')_fetching_history_const_win_awaii18n_i18n.t('ui_const_win_awaii18n_t')ui_i18n_t_ui_i18n_t_ui_ctx_windowi18n.t('ui_i18n_t_ui_i18n_t_ui_ctx_window_get')       const data = win.content
        const size = win.tokens
     i18n.t('ui_i18n_t_ui_ctx_window_get')ta, "i18n.t('ui_i18n_t_ui_ctx_window_get')_ui_i18n_t_ui_mi18n.t('ui_i18n_t_ui_i18n_t_ui_markdown')size} tokens`, "i18n.t('ui_i18n_t_ui_i18n_t_ui_ii18n.t('ui_i18n_t_ui_i18n_t_ui_data_passed_to_the_llm_durini18n_t')arkdown_ntains_system_mi18n.t('ui_ntains_system_message_conversatii18n.t('ui_context_window_size_tokens')ed_to_the_llm_during_last_interaction_contains_si18n_t_ui_context_window_i18n.t('ui_context_window_size_tokens')" + e.message, i18n.t('ui_xt')8n.t('ui_i18n_t_ui_i18n_t_i18n.t('ui_i18n_t_ui_i18n_t_ui_context_error')'ui_i18n_t_i18n.t('ui_i18n_t_ui_error_fetching_context')howEditorModal(dati18n.t('ui_i18n_t_i18n.t('ui_i18n_t_ui_context_error')8n_t_ui_json')"i18n.t('i18n.t('ui_title_description_i18n_t')_i18n_t_ui_i18n_t_ui_i18n_t_ui_geneii18n.t('ui_i18n_t_ui_json')i_json_h_json_viewer_container_const_html_di18i18n.t('ui_i18n_t_ui_generate_the_html_with_json_viewer_container_const_html_div_id')v_id_odal_with_the_generated_html_awaii18n_i18n.t('ui_i18n_t_ui_div_open_the_modal_with_the_generated_html_await_window_genericmodalproxy_openmodal_title_description_html')ml_the_json_viewer_after_the_i18n_t_i18n.t('ui_i18n_t_ui_initialize_the_json_viewer_after_the_modal_is_rendered_const_container_document_getelementbyid')_t_ui_if_container_const_editor_ai18n_t_ui_i18n.t('ui_i18n_t_ui_if_container_const_editor_ace_edit')ui_i18n_t_ui_const_dark_localsi18n_t_ui_i18i18n.t('ui_i18n_t_ui_const_dark_localstorage_getitem_darkmode_if_dark')t_ui_editor_i18n_t_ui_i18n_i18n.t('ui_i18n_t_ui_editor_settheme')i18n.t('ui_i18ni18n.t('ui_i18n_t_ui_i18n_t_i18n_t')n_t_ui_else_editor_settheme')me/tomi18n.t('ui_me_tomorrow_i18n_t')n_t_ui_i18n_t_i18n_i18n.t('ui_i18n_t_ui_editor_session_setmode')de')"ace/mode/" + type);
        editor.setValue(data);
        editor.clearSelection();
        // editor.session.$toggleFoldWidget(5, {})
    }
}

window.openHistoryModal = openHistoryModal;
window.openCtxWindowModal = openCtxWindowModal;
