// Singleton interval ID for image refresh
let activeIntervalId = null;

export async function openImageModal(src, refreshInterval = 0) {
  try {
    let imgSrc = src;

    // Clear any existing refresh interval
    if (activeIntervalId !== null) {
      clearInterval(activeIntervalId);
      activeIntervalId = null;
    }

    if (refreshInterval > 0) {
      // Add or update timesti18n.t('ui_0_adi18n.t('ui_0_add_or_update_timesti1i18n.t('ui_0_adi18n_t')('ui_0_adi18n_t')e_timestamp_to_bypass_cachei18n.t('ui_0_adi18n_t')estamp_url_const_urlobj_new_url_url_window_location_origin_urlobj_searchparams_set_t_date_now_return_urlobj_tostring_check_if_image_viewer_is_still_active_const_isimagevieweractive_const_container_document_queryselector_image_viewer_container_if_container_return_false_check_if_element_or_any_parent_is_hidden_let_element_container_while_element_const_style_window_getcomputedstyle_element_if_style_display_none_style_visibility_hidden_style_opacity_0_return_false_element_element_parentelement_return_true_preload_next_image_before_displaying_const_preloadandupdate_async_currentimg_const_nextsrc_addtimestamp_src_create_a_promise_that_resolves_when_the_image_is_loaded_const_preloadpromise_new_promise_resolve_reject_const_tempimg_new_image_tempimg_onload_resolve_nextsrc_tempimg_onerror_reject_tempimg_src_nextsrc_try_wait_for_preload_to_complete_const_loadedsrc_await_preloadpromise_check_if_this_interval_is_still_the_active_one_if_currentimg_isimagevieweractive_currentimg_src_loadedsrc_catch_err_console_error_failed_to_preload_image_err_imgsrc_addtimestamp_src_set_up_periodic_refresh_with_preloading_activeintervalid_setinterval_if_isimagevieweractive_clearinterval_activeintervalid_activeintervalid_null_return_const_img_document_queryselector_image_viewer_img_if_img_preloadandupdate_img_refreshinterval_const_html_ontainer')')"i18n.t('ui_i18n_t_ui_i18n_t_ui_src')"i18i18n.t('ui_i18n_t')mgsrc')"i18n.t('uii18n.t('ui_i18n_t')ui_i18n_t_ii18n.t('ui_ii18n_t')_t_ui_i18n_i18n.t('ui_i18n_t_i18n_t')n_t_ui_i18ni18n.t('ui_nst_filenami18n_t')i_i18n_t_uii18n.t('ui_it')8n_t_ui_i18n_i18n.t('ui_i18n_t_ui_i18n_i18n_t')odal_with_ti18n.t('ui_en_the_modal_with_the_generated_html_await_window_genericmodalproxy_openmodal_filename')t_ui_i18n_tii18n.t('ui_i18n_ti18n_t')ui_html_cati18n.t('ui_html_catch_e_window_toastfrontenderror')8n.t('ui_error_fetci18n.t('ui_error_fetching_history_i18n_t')ui_e_message')"i18n.t('ui_image_history_error')");
    return;
  }
}
