{{- $c := .Values.certManager -}}
{{- if $c.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $c.clusterIssuer.name }}
spec:
  acme:
    email: {{ $c.email | quote }}
    server: {{ $c.clusterIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ printf "%s-key" $c.clusterIssuer.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
