{{- $v := .Values.ingressNginx -}}
{{- if $v.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soma-infra.fullname" . }}-ingress-nginx-controller
  labels:
    app.kubernetes.io/name: ingress-nginx-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: default
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "soma-infra.imagePullSecrets" . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: {{ $v.image | quote }}
          args:
            - /nginx-ingress-controller
            - --ingress-class=nginx
            - --controller-class=k8s.io/ingress-nginx
            - --publish-status-address=localhost
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml $v.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "soma-infra.fullname" . }}-ingress-nginx-controller
  labels:
    app.kubernetes.io/name: ingress-nginx-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ $v.service.type }}
  selector:
    app.kubernetes.io/name: ingress-nginx-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      {{- if eq $v.service.type "NodePort" }}
      nodePort: {{ $v.service.httpNodePort }}
      {{- end }}
    - name: https
      port: 443
      targetPort: https
      {{- if eq $v.service.type "NodePort" }}
      nodePort: {{ $v.service.httpsNodePort }}
      {{- end }}
{{- end }}
