{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "soma-infra.fullname" . }}-default-deny
  labels:
    {{- include "soma-infra.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
{{- $labelKey := .Values.networkPolicy.allowedNamespaceLabel.key | default "soma.sh/allow-shared-infra" }}
{{- $labelValue := .Values.networkPolicy.allowedNamespaceLabel.value | default "true" }}
{{- $services := list
    (dict "name" "postgres"    "ports" (list 5432))
    (dict "name" "redis"       "ports" (list 6379))
    (dict "name" "opa"         "ports" (list 8181))
    (dict "name" "vault"       "ports" (list 8200))
    (dict "name" "prometheus"  "ports" (list 9090))
    (dict "name" "etcd"        "ports" (list 2379 2380))
    (dict "name" "kafka"       "ports" (list 9092 9093))
  }}
{{- range $index, $service := $services }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-allow-%s" (include "soma-infra.fullname" $) ($service.name) }}
  labels:
    {{- include "soma-infra.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      component: {{ $service.name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{ $labelKey }}: {{ $labelValue | quote }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $.Release.Namespace }}
      ports:
        {{- range $service.ports }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
  policyTypes:
    - Ingress
{{- if lt (add $index 1) (len $services) }}
---
{{- end }}
{{- end }}
{{- end }}
