apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    component: vault
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vault.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: vault
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: vault
          image: {{ .Values.image | default "hashicorp/vault:latest" }}
          imagePullPolicy: IfNotPresent
          args:
            - "server"
            - "-dev"
            - "-dev-listen-address=0.0.0.0:8200"
          env:
            {{- $secretName := .Values.server.secret.name | default (printf "%s-dev-root" (include "vault.fullname" .)) }}
            - name: {{ .Values.server.secret.envVar | default "VAULT_DEV_ROOT_TOKEN_ID" }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .Values.server.secret.tokenKey }}
          ports:
            - containerPort: 8200
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
