{{- if .Values.component }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soma-infra.fullname" . }}-{{ .Values.component.name }}
  labels:
    {{- include "soma-infra.labels" . | nindent 4 }}
    component: {{ .Values.component.name | quote }}
spec:
  replicas: {{ .Values.component.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "soma-infra.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: {{ .Values.component.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "soma-infra.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        component: {{ .Values.component.name | quote }}
    spec:
      containers:
        - name: {{ .Values.component.name | quote }}
          image: "{{- if .Values.component.image -}}{{ .Values.component.image -}}{{ else -}}{{ .Values.image | default "" }}{{- end }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy | default "IfNotPresent" }}"
          ports:
            - containerPort: {{ default 80 .Values.component.port }}
          env:
            - name: SEMA_ENV
              value: "{{ .Release.Namespace }}"
{{- end }}
