"""Module 0001_initial."""

# Generated by Django 6.0 on 2025-12-25 05:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class implementation."""

    initial = True

    dependencies = [
        ("llm", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceModel",
            fields=[
                ("id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("provider", models.CharField(default="kokoro", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female"), ("neutral", "Neutral")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sample_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Voice Model",
                "verbose_name_plural": "Voice Models",
                "db_table": "voice_models",
                "ordering": ["provider", "name"],
                "indexes": [
                    models.Index(
                        fields=["provider", "is_active"], name="voice_model_provide_76c4f5_idx"
                    ),
                    models.Index(fields=["language"], name="voice_model_languag_f3e3dc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoicePersona",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="Tenant ID for multi-tenancy isolation"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "voice_id",
                    models.CharField(
                        default="af_heart", help_text="Kokoro voice ID", max_length=50
                    ),
                ),
                ("voice_speed", models.FloatField(default=1.0)),
                (
                    "stt_model",
                    models.CharField(
                        choices=[
                            ("tiny", "Whisper Tiny"),
                            ("small", "Whisper Small"),
                            ("medium", "Whisper Medium"),
                            ("large", "Whisper Large"),
                        ],
                        default="tiny",
                        max_length=50,
                    ),
                ),
                ("stt_language", models.CharField(default="en", max_length=10)),
                ("system_prompt", models.TextField(blank=True)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=1024)),
                ("turn_detection_enabled", models.BooleanField(default=True)),
                ("turn_detection_threshold", models.FloatField(default=0.5)),
                ("silence_duration_ms", models.IntegerField(default=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "llm_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to existing LLM model configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_personas",
                        to="llm.llmmodelconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Persona",
                "verbose_name_plural": "Voice Personas",
                "db_table": "voice_personas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="Tenant ID for multi-tenancy isolation"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("api_key_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("audio_input_seconds", models.FloatField(default=0.0)),
                ("audio_output_seconds", models.FloatField(default=0.0)),
                ("turn_count", models.IntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="voice.voicepersona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Session",
                "verbose_name_plural": "Voice Sessions",
                "db_table": "voice_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voicepersona",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="voice_perso_tenant__25c392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicepersona",
            index=models.Index(fields=["is_default"], name="voice_perso_is_defa_c1a865_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="voicepersona",
            unique_together={("tenant_id", "name")},
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(
                fields=["tenant_id", "status"], name="voice_sessi_tenant__753842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(fields=["project_id"], name="voice_sessi_project_4ad10a_idx"),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(fields=["api_key_id"], name="voice_sessi_api_key_4e3653_idx"),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(fields=["-created_at"], name="voice_sessi_created_3f4187_idx"),
        ),
    ]
