replicaCount: 1

image:
  repository: quay.io/coreos/etcd
  tag: "v3.5.12"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2379
  clientPort: 2379
  peerPort: 2380

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  # Persistence disabled for local Kind testing (no default storage class)
  enabled: false
  size: 1Gi
  storageClass: ""

nodeSelector: {}

tolerations: []

affinity: {}
