image: confluentinc/cp-kafka:7.5.3
replicaCount: 1
service:
  type: ClusterIP
  port: 9092
  targetPort: 9092
controllerPort: 9093
clusterId: TelVMif65nMWlbOjBdhrJw
nodeId: "1"
env:
  extra: []
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi
