"""Module 0001_initial."""

# Generated by Django 5.1.4 on 2026-01-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class implementation."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[("chat", "Chat"), ("embedding", "Embedding")],
                        default="chat",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("api_base", models.URLField(blank=True, default="")),
                ("ctx_length", models.IntegerField(default=0)),
                ("limit_requests", models.IntegerField(default=0)),
                ("limit_input", models.IntegerField(default=0)),
                ("limit_output", models.IntegerField(default=0)),
                ("vision", models.BooleanField(default=False)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Model Configuration",
                "verbose_name_plural": "LLM Model Configurations",
                "db_table": "llm_model_configs",
                "ordering": ["provider", "name"],
            },
        ),
    ]
