# Generated by Django 5.1.4 on 2026-01-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_add_capabilities_routing"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="llmmodelconfig",
            new_name="llm_model_c_is_acti_1e0095_idx",
            old_name="llm_model_c_is_acti_routing_idx",
        ),
        migrations.RenameIndex(
            model_name="llmmodelconfig",
            new_name="llm_model_c_provide_2a722e_idx",
            old_name="llm_model_c_provide_active_idx",
        ),
        migrations.AlterField(
            model_name="llmmodelconfig",
            name="ctx_length",
            field=models.IntegerField(default=0, help_text="Max context length in tokens"),
        ),
        migrations.AlterField(
            model_name="llmmodelconfig",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="llmmodelconfig",
            name="limit_input",
            field=models.IntegerField(default=0, help_text="Max input tokens per request"),
        ),
        migrations.AlterField(
            model_name="llmmodelconfig",
            name="limit_output",
            field=models.IntegerField(default=0, help_text="Max output tokens per request"),
        ),
        migrations.AlterField(
            model_name="llmmodelconfig",
            name="limit_requests",
            field=models.IntegerField(default=0, help_text="Rate limit: requests/min"),
        ),
    ]
