# Generated by Django 6.0 on 2025-12-25 03:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_destructive", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "permissions_action",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PermissionCheckLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "tenant_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("permission_codename", models.CharField(max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=255, null=True)),
                ("allowed", models.BooleanField()),
                ("reason", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "permissions_check_log",
                "indexes": [
                    models.Index(
                        fields=["user_id", "timestamp"], name="permissions_user_id_26d72c_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "timestamp"], name="permissions_tenant__2c2474_idx"
                    ),
                    models.Index(
                        fields=["allowed", "timestamp"], name="permissions_allowed_015df7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionResource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=50)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to Django model",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "permissions_resource",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="GranularPermission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="permissions.permissionaction",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="permissions.permissionresource",
                    ),
                ),
            ],
            options={
                "db_table": "permissions_granular",
                "ordering": ["resource__name", "action__name"],
                "unique_together": {("resource", "action")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant ID for multi-tenancy isolation",
                        max_length=255,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("platform", "Platform-wide"),
                            ("tenant", "Tenant-scoped"),
                            ("agent", "Agent-scoped"),
                        ],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be modified or deleted"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Default role for new users"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="permissions.granularpermission"
                    ),
                ),
            ],
            options={
                "db_table": "permissions_role",
                "ordering": ["name"],
                "unique_together": {("tenant_id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PermissionGrant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant ID for multi-tenancy isolation",
                        max_length=255,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("scope_type", models.CharField(default="tenant", max_length=20)),
                (
                    "scope_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("granted_by", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="permissions.granularpermission",
                    ),
                ),
            ],
            options={
                "db_table": "permissions_grant",
                "indexes": [
                    models.Index(
                        fields=["user_id", "tenant_id"], name="permissions_user_id_1cf565_idx"
                    ),
                    models.Index(
                        fields=["user_id", "permission"], name="permissions_user_id_b6b391_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant ID for multi-tenancy isolation",
                        max_length=255,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("scope_type", models.CharField(default="tenant", max_length=20)),
                (
                    "scope_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of specific resource (e.g., agent_id)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("granted_by", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "db_table": "permissions_user_role",
                "indexes": [
                    models.Index(
                        fields=["user_id", "tenant_id"], name="permissions_user_id_12d145_idx"
                    ),
                    models.Index(
                        fields=["user_id", "scope_type", "scope_id"],
                        name="permissions_user_id_ea0eb7_idx",
                    ),
                ],
            },
        ),
    ]
