image: openpolicyagent/opa:latest
replicaCount: 1
service:
  type: ClusterIP
  port: 8181
  targetPort: 8181
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
