kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: soma-ingress
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        listenAddress: 0.0.0.0
        protocol: TCP
  - role: worker
