kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: soma-ingress
nodes:
	- role: control-plane
		extraPortMappings:
			# Map host 80/443 to the ingress-nginx NodePorts (30080/30443)
			- containerPort: 30080
				hostPort: 80
				protocol: TCP
			- containerPort: 30443
				hostPort: 443
				protocol: TCP
	- role: worker
