# Production environment overrides for soma-infra

namespace: soma-infra
imagePullPolicy: IfNotPresent

auth:
  enabled: true
  replicaCount: 3

opa:
  enabled: true
  replicaCount: 3

kafka:
  enabled: true
  replicaCount: 3  # minimum HA

redis:
  enabled: true
  replicaCount: 3  # cluster

prometheus:
  enabled: true
  replicaCount: 2

grafana:
  enabled: true
  replicaCount: 2

vault:
  enabled: true
  replicaCount: 3

etcd:
  enabled: true
  replicaCount: 3
