"""Module 0001_flink_sink_tables."""

# Generated by Django 6.0 on 2025-12-25 03:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    """Migration class implementation."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlinkAgentMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("agent_id", models.CharField(db_index=True, max_length=255)),
                ("window_start", models.DateTimeField(db_index=True)),
                ("window_end", models.DateTimeField()),
                ("total_requests", models.BigIntegerField(default=0)),
                ("successful_requests", models.BigIntegerField(default=0)),
                ("failed_requests", models.BigIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0.0)),
                ("p95_response_time_ms", models.FloatField(default=0.0)),
                ("tokens_consumed", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "flink_agent_metrics",
                "ordering": ["-window_start"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "window_start"], name="flink_agent_tenant__30103d_idx"
                    ),
                    models.Index(
                        fields=["agent_id", "window_start"], name="flink_agent_agent_i_8ac94e_idx"
                    ),
                ],
                "unique_together": {("agent_id", "window_start")},
            },
        ),
        migrations.CreateModel(
            name="FlinkAnomalyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("HIGH_DENIAL_RATE", "High Permission Denial Rate"),
                            ("BRUTE_FORCE", "Brute Force Attack"),
                            ("UNUSUAL_ACTIVITY", "Unusual Activity Pattern"),
                            ("DATA_EXFILTRATION", "Potential Data Exfiltration"),
                            ("PRIVILEGE_ESCALATION", "Privilege Escalation Attempt"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField()),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_by", models.CharField(blank=True, max_length=255, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "flink_anomaly_alerts",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "detected_at"], name="flink_anoma_tenant__0a9f88_idx"
                    ),
                    models.Index(
                        fields=["severity", "acknowledged"], name="flink_anoma_severit_2d90a1_idx"
                    ),
                    models.Index(fields=["alert_type"], name="flink_anoma_alert_t_c649ec_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FlinkConversationMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("window_start", models.DateTimeField(db_index=True)),
                ("window_end", models.DateTimeField()),
                ("total_conversations", models.BigIntegerField(default=0)),
                ("total_messages", models.BigIntegerField(default=0)),
                ("total_tokens", models.BigIntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("unique_users", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "flink_conversation_metrics",
                "ordering": ["-window_start"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "window_start"], name="flink_conve_tenant__5986e4_idx"
                    ),
                    models.Index(fields=["window_start"], name="flink_conve_window__48cf6c_idx"),
                ],
                "unique_together": {("tenant_id", "window_start")},
            },
        ),
        migrations.CreateModel(
            name="FlinkSystemMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("window_start", models.DateTimeField(db_index=True)),
                ("window_end", models.DateTimeField()),
                ("total_api_requests", models.BigIntegerField(default=0)),
                ("total_active_conversations", models.BigIntegerField(default=0)),
                ("total_active_agents", models.BigIntegerField(default=0)),
                ("total_active_users", models.BigIntegerField(default=0)),
                ("avg_api_latency_ms", models.FloatField(default=0.0)),
                ("error_rate", models.FloatField(default=0.0)),
                ("total_tokens_consumed", models.BigIntegerField(default=0)),
                ("total_storage_bytes", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "flink_system_metrics",
                "ordering": ["-window_start"],
                "indexes": [
                    models.Index(fields=["window_start"], name="flink_syste_window__d822bf_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="FlinkUsageAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("resource_type", models.CharField(max_length=50)),
                ("window_start", models.DateTimeField(db_index=True)),
                ("total_quantity", models.BigIntegerField(default=0)),
                ("event_count", models.BigIntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("billed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "flink_usage_aggregates",
                "ordering": ["-window_start"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "window_start"], name="flink_usage_tenant__5333cf_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "billed"], name="flink_usage_tenant__9d2952_idx"
                    ),
                ],
                "unique_together": {("tenant_id", "resource_type", "window_start")},
            },
        ),
    ]