"""Module 0002_llm_token_tracking."""

# Generated by Django 6.0 on 2025-12-25 03:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    """Migration class implementation."""

    dependencies = [
        ("flink", "0001_flink_sink_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlinkLLMModelUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("agent_id", models.CharField(db_index=True, max_length=255)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateField(db_index=True)),
                ("total_requests", models.BigIntegerField(default=0)),
                ("total_tokens", models.BigIntegerField(default=0)),
                ("prompt_tokens", models.BigIntegerField(default=0)),
                ("completion_tokens", models.BigIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0.0)),
                ("error_rate", models.FloatField(default=0.0)),
                ("total_cost_usd", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "flink_llm_model_usage",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "date"], name="flink_llm_m_tenant__3ccc12_idx"
                    ),
                    models.Index(
                        fields=["model_name", "date"], name="flink_llm_m_model_n_ba8e4d_idx"
                    ),
                ],
                "unique_together": {("tenant_id", "agent_id", "model_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="FlinkLLMTokenMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=255)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("window_start", models.DateTimeField(db_index=True)),
                ("window_end", models.DateTimeField()),
                ("prompt_tokens", models.BigIntegerField(default=0)),
                ("completion_tokens", models.BigIntegerField(default=0)),
                ("total_tokens", models.BigIntegerField(default=0)),
                ("request_count", models.BigIntegerField(default=0)),
                ("successful_requests", models.BigIntegerField(default=0)),
                ("failed_requests", models.BigIntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("p95_latency_ms", models.FloatField(default=0.0)),
                ("p99_latency_ms", models.FloatField(default=0.0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "flink_llm_token_metrics",
                "ordering": ["-window_start"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "window_start"], name="flink_llm_t_tenant__b82c34_idx"
                    ),
                    models.Index(
                        fields=["model_name", "window_start"], name="flink_llm_t_model_n_46428a_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "model_name"], name="flink_llm_t_tenant__c19e8b_idx"
                    ),
                ],
                "unique_together": {("tenant_id", "model_name", "window_start")},
            },
        ),
    ]