apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: somaagent01
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/part-of: somaagent01
    spec:
      containers:
        - name: gateway
          image: agent0ai/agent-zero:latest
          imagePullPolicy: IfNotPresent
          command: ["uvicorn"]
          args:
            - "services.gateway.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8010"
          ports:
            - containerPort: 8010
              name: http
          env:
            - name: PORT
              value: "8010"
          envFrom:
            - configMapRef:
                name: somaagent-config
            - secretRef:
                name: somaagent-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
