# Generated by Django 5.1.4 on 2026-09-27 16:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aaas", "0004_platformconfig_delete_globaldefault_and_more"),
        ("core", "0008_asset_delegationtask_executionrecord_modelprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("web", "Web"),
                        ],
                        db_index=True,
                        help_text="Channel network: whatsapp/telegram/email/slack/web",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="disabled",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Channel config (allowlists, group mode, poll interval, …)",
                    ),
                ),
                (
                    "credentials_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vault/secrets-store reference for channel credentials — never raw secrets",
                        max_length=512,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capsule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Capsule that answers on this channel; unbound = fail-closed dispatch",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bridge_channels",
                        to="core.capsule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant; required — no default tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bridge_channels",
                        to="aaas.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "bridge_channels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BridgeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="External user identifier (WA JID, TG user id, email address)",
                        max_length=255,
                    ),
                ),
                (
                    "external_chat_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="External chat/group/thread identifier when distinct from user",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Session context (thread markers, group metadata, slash state)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="bridges.channel",
                    ),
                ),
            ],
            options={
                "db_table": "bridge_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InboundMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Message id on the external network (for dedupe)",
                        max_length=255,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        default="inbound",
                        help_text="Message direction marker (inbound)",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Normalized inbound payload (text, sender, chat, raw ref)",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Attachment descriptors (media type, vault/storage ref)",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when dispatched to the agent; null = unprocessed",
                        null=True,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_messages",
                        to="bridges.channel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_messages",
                        to="bridges.bridgesession",
                    ),
                ),
            ],
            options={
                "db_table": "bridge_inbound_messages",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Outbound payload (text/markdown, reply_to, media refs)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Idempotency key to prevent double-send",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_messages",
                        to="bridges.channel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_messages",
                        to="bridges.bridgesession",
                    ),
                ),
            ],
            options={
                "db_table": "bridge_outbound_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["tenant", "kind"], name="bridge_chan_tenant__7ff356_idx"),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["status"], name="bridge_chan_status_547ad9_idx"),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name", ""), _negated=True),
                fields=("tenant", "kind", "name"),
                name="bridge_channel_unique_name_per_tenant_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="bridgesession",
            index=models.Index(
                fields=["channel", "external_user_id", "external_chat_id"],
                name="bridge_sess_channel_6a04c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundmessage",
            index=models.Index(
                fields=["channel", "external_id"], name="bridge_inbo_channel_91dec8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundmessage",
            index=models.Index(
                fields=["status", "created_at"], name="bridge_outb_status_bd0e73_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("idempotency_key", None), _negated=True),
                    models.Q(("idempotency_key", ""), _negated=True),
                ),
                fields=("channel", "idempotency_key"),
                name="bridge_outbound_idempotency_unique",
            ),
        ),
    ]
