apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa.fullname" . }}
  labels:
    {{- include "opa.labels" . | nindent 4 }}
    component: opa
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "opa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: opa
