# Generated by Django 5.1.4 on 2026-05-26 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemoryConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "retention_days",
                    models.IntegerField(default=30, help_text="Days to keep ephemeral memories"),
                ),
                (
                    "archival_days",
                    models.IntegerField(default=365, help_text="Days to keep archival memories"),
                ),
                (
                    "vector_db_collection",
                    models.CharField(
                        blank=True, help_text="Specific collection/namespace", max_length=255
                    ),
                ),
                ("snapshot_frequency_hours", models.IntegerField(default=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Memory Configuration",
                "db_table": "somabrain_memory_config",
            },
        ),
    ]
