image: prom/prometheus:latest
replicaCount: 1
service:
  type: ClusterIP
  port: 9090
  targetPort: 9090
config:
  global:
    scrape_interval: 15s
  scrape_configs: []
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 600m
    memory: 1Gi
