{{- if .Values.services.delegationWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soma-stack.fullname" . }}-delegation-worker
  labels:
    app.kubernetes.io/name: delegation-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.services.delegationWorker.replicas | default .Values.global.REPLICA_COUNT }}
  selector:
    matchLabels:
      app.kubernetes.io/name: delegation-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: delegation-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- include "soma-stack.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "soma-stack.saName" . }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- include "soma-stack.imagePullSecrets" . | nindent 8 }}
      {{- end }}
      containers:
        - name: delegation-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python3", "-m", "services.delegation_worker.main"]
          env:
            - name: POSTGRES_DSN
              value: {{ .Values.env.POSTGRES_DSN | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
            - name: JWT_ENABLED
              value: {{ .Values.global.JWT_ENABLED | quote }}
            - name: OPA_ENABLED
              value: {{ .Values.global.OPA_ENABLED | quote }}
            - name: MTLS_ENABLED
              value: {{ .Values.global.MTLS_ENABLED | quote }}
            - name: PROMETHEUS_SCRAPE
              value: {{ .Values.global.PROMETHEUS_SCRAPE | quote }}
            - name: OTEL_ENABLED
              value: {{ .Values.global.OTEL_ENABLED | quote }}
          resources:
            requests:
              cpu: {{ .Values.global.RESOURCE_REQUESTS.cpu | quote }}
              memory: {{ .Values.global.RESOURCE_REQUESTS.memory | quote }}
            limits:
              cpu: {{ .Values.global.RESOURCE_LIMITS.cpu | quote }}
              memory: {{ .Values.global.RESOURCE_LIMITS.memory | quote }}
{{- end }}
