{{- $g := .Values.global -}}
{{- $svc := .Values.services.gateway -}}
{{- if and $g.ISTIO_ENABLED $svc.enabled $svc.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "soma-stack.fullname" . }}-gateway
spec:
  host: {{ include "soma-stack.fullname" . }}-gateway.{{ .Release.Namespace }}.svc.cluster.local
  {{- with $svc.istio.trafficPolicy }}
  trafficPolicy:
    {{- if .connectionPool }}
    connectionPool:
      {{- if .connectionPool.tcp }}
      tcp:
        {{- toYaml .connectionPool.tcp | nindent 8 }}
      {{- end }}
      {{- if .connectionPool.http }}
      http:
        {{- toYaml .connectionPool.http | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .outlierDetection }}
    outlierDetection:
      {{- toYaml .outlierDetection | nindent 6 }}
    {{- end }}
  {{- end }}
  subsets:
    - name: stable
      labels:
        track: stable
    - name: canary
      labels:
        track: canary
{{- end }}
