{{- if .Values.global.NETWORK_POLICY_ENABLED }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "soma-stack.fullname" . }}-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    {{- $allowed := .Values.global.NETWORK_POLICY_ALLOWED_NAMESPACE_LABEL }}
    {{- if and $allowed $allowed.key $allowed.value }}
    - to:
        - namespaceSelector:
            matchLabels:
              {{ $allowed.key }}: {{ $allowed.value | quote }}
      ports:
        # Postgres
        - protocol: TCP
          port: 5432
        # Redis
        - protocol: TCP
          port: 6379
        # Kafka (broker/controller)
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093
        # OPA / OpenFGA / Vault (typical)
        - protocol: TCP
          port: 8181
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8200
    {{- end }}
{{- end }}