{{- if .Values.global.PROM_OPERATOR_ENABLED }}
{{- if .Values.services.gateway.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soma-stack.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      interval: 30s
{{- end }}
{{- if .Values.services.conversationWorker.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soma-stack.fullname" . }}-conversation-worker
  labels:
    app.kubernetes.io/name: conversation-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: conversation-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
{{- if .Values.services.toolExecutor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soma-stack.fullname" . }}-tool-executor
  labels:
    app.kubernetes.io/name: tool-executor
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tool-executor
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
{{- if .Values.services.memoryReplicator.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soma-stack.fullname" . }}-memory-replicator
  labels:
    app.kubernetes.io/name: memory-replicator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memory-replicator
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
{{- if .Values.services.delegationGateway.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soma-stack.fullname" . }}-delegation-gateway
  labels:
    app.kubernetes.io/name: delegation-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: delegation-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      interval: 30s
{{- end }}
{{- if .Values.services.ui.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soma-stack.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      interval: 30s
{{- end }}
{{- end }}
