apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "soma-stack.fullname" . }}-ui-test
  labels:
    app.kubernetes.io/name: ui-test
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui-test
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:8.10.1
          args:
            - -fsS
            - http://{{ include "soma-stack.fullname" . }}-ui:{{ .Values.services.ui.port }}/
