# Generated by Django 5.1.4 on 2026-01-02 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("agent_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("memory_mode", models.CharField(default="persistent", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "status"], name="conversatio_user_id_f1418c_idx"
                    ),
                    models.Index(
                        fields=["agent_id", "status"], name="conversatio_agent_i_1e4d27_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "user_id"], name="conversatio_tenant__1a8b8e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("conversation_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("participant", "Participant"),
                            ("observer", "Observer"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "conversation_participants",
                "indexes": [
                    models.Index(
                        fields=["user_id", "conversation_id"], name="conversatio_user_id_bb37a4_idx"
                    )
                ],
                "unique_together": {("conversation_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("conversation_id", models.UUIDField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("token_count", models.IntegerField(default=0)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation_id", "created_at"], name="messages_convers_3ebb41_idx"
                    )
                ],
            },
        ),
    ]
