# Generated by Django 5.1.4 on 2026-01-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.AddField(
            model_name="message",
            name="coordinate",
            field=models.CharField(db_index=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="message",
            name="feedback_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="feedback_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("explicit", "Explicit"),
                    ("implicit", "Implicit"),
                    ("self_eval", "Self Evaluation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="rating",
            field=models.FloatField(blank=True, help_text="User feedback 0.0-1.0", null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="synced_to_brain",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="task_type",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="tools_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["task_type", "rating"], name="messages_task_ty_1a9d09_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["model", "task_type"], name="messages_model_45f708_idx"),
        ),
    ]
