# Generated by Django 5.1.4 on 2026-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_content_use_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="coordinate",
            field=models.TextField(default=""),
        ),
    ]
