apiVersion: v1
kind: Service
metadata:
  name: canvas-service
  labels:
    app.kubernetes.io/name: canvas-service
    app.kubernetes.io/part-of: somaagent01
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: canvas-service
  ports:
    - name: http
      port: 8014
      targetPort: http
