apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/part-of: somaagent01
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: router
        app.kubernetes.io/part-of: somaagent01
    spec:
      containers:
        - name: router
          image: agent0ai/agent-zero:latest
          imagePullPolicy: IfNotPresent
          command: ["uvicorn"]
          args:
            - "services.router.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8013"
          ports:
            - containerPort: 8013
              name: http
          env:
            - name: PORT
              value: "8013"
          envFrom:
            - configMapRef:
                name: somaagent-config
            - secretRef:
                name: somaagent-secrets
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
