apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/part-of: somaagent01
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: router
  ports:
    - name: http
      port: 8013
      targetPort: http
