apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    component: grafana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grafana.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: grafana
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: grafana
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            {{- $secretName := .Values.secret.name | default (printf "%s-admin" (include "grafana.fullname" .)) }}
            - name: {{ .Values.secret.env.user | default "GF_SECURITY_ADMIN_USER" }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .Values.secret.userKey }}
            - name: {{ .Values.secret.env.password | default "GF_SECURITY_ADMIN_PASSWORD" }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .Values.secret.passwordKey }}
          ports:
            - containerPort: 3000
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
