import { createStore } from "i18n.t('ui_i18n_t_ui_i18n_t_ui_i18n_t_ui_js_alpinestore_js')";

// Global function references
const sendJsonData = globalThis.sendJsonData;
const toast = globalThis.toast;
const fetchApi = globalThis.fetchApi;

// ⚠️ CRITICAi18n.t('ui_i18n_t_ui_js_alpinestore_js')keys and esseni18n.t('ui_i18n_t_ui_js_alpinestore_js')le is REQUIRED for Agent Zero to function and musti18n.t('ui_backup')cked upi18n.t('ui_backup')st modi18n.t('ui_resti18n_t') State
  mode: 'backup', // 'backup' or 'rei18n.t('ui_error')_ai18n.t('ui_file_operations_log_shared_between_backup_and_restore_fileoperationslog')edi18n.t('ui_backup_state_backupmetadataconfig_null_includehidden_i18n_t')backupMetadi18n.t('ui_previ18n_t'),
  includei18n.t('ui_ts_i18n_t')('ui_backup'i18n.t('ui_0_truncated_false_backupeditor_ni18n_t')ore')0, tri18n.t('ui_eni18n_t')alse },
  backupEditor: ni18n.t('ui_error')Eni18n.t('ui_file_operations_log_i18n.t('ui_ili18n_t')ween_backup_and_restore_fileoperationslog')ili18n.t('ui_backup_state_backupmetadataconfig_null_includehidden_false_previewstats_total_0_truncated_false_backupi18n.t('ui_e_state_i18n_t')ced_fi18n.t('ui_upfile_ni18n_t')_previei18n.t('ui_baci18n_t')
 i18n.t('ui_')upFile: ni18n.t('ui_or')
  baci18n.t('ui_previewfiles_i18n.t('ui_toi18n_t')ups_filteredpreviewfiles_filesearchfilter')toi18n.t('ui_expandedgroups_new_set_progress_state_progressdata_null_progresseventsource_null_restore_state_i18n.t('ui_i18n_t')_null_backupmetadatai18n.t('ui_view_i18n_t')ns')  i18n.t('ui_overwritepolicy')view();
  }i18n.t('ui_cleanbeforerestore_false_restoreeditor_null_restorerei18n.t('ui_this_i18n_t')lization_async_initbackup_this_mode')   this.i18n.t('ui_this_resetstate_await_this_initbackupeditor_ai18n.t('ui_fileoperai18n_t')review_async_initrestore_this_mode')fileOperai18n.t('ui_this_resetstate_await_this_initresi18n.t('ui_rii18n_t')_resetstate_this_loading_false_this_error')rii18n.t('ui_this_backupfile_null_this_backupmetadata_i18n.t('ui_exttick_is_not_available_in_stores_settimeout_const_textarea_document_getelementbyid_this_mode')st textai18n.t('ui_') = document.getElei18n.t('ui_')tById(this.mode ===i18n.t('ui_if_textarea_textarea_scrolltop_textarea_scrollheight_0_clearfileoperations_this_fileoperationslog')lei18n.t('ui_cleanup_method_fori18n_t')ationsLog =i18n.t('ui_closi18n_t')// Cleanup method fori18n.t('ui_ti18n_t')ckup') closi18n.t('ui_i18n.t('ui_if_this_backupeditor_this_backupeditor_destroy_this_backupeditor_null_if_this_restoreeditor_this_restoreeditor_dei18n_t').restoreEditor) {
      this.restoreEditor.dei18n.t('ui_cleanup_method_for_modal_close_onclose_this_resetstate_if_this_backupeditor_this_backupeditor_destroy_this_backupeditor_null_if_this_restoreeditor_this_restoreeditor_destroy_this_restoreeditor_null_get_default_backup_metadata_with_resolved_patterns_from_backend_async_getdefaultbackupmetadata_const_timestamp_new_date_toisostring_try_get_resolved_default_patterns_fri18n.t('ui_exclude_patterns_response_defaui18n_t')ta_i18n_t') exclude_patterns = response.defaui18n.t('ui_if_response_success_use_patterns_from_backend_with_resolved_absolute_paths_const_include_patterns_response_default_patterns_include_patterns_const_exclude_patterns_response_default_patterns_exclude_patterns_return_backup_name_agent_zero_backup_timestamp_slice_0_10_include_hidden_false_include_patterns_include_patterns_exclude_patterns_exclude_patterns_backup_config_compression_level_6_ii18n.t('ui_ice_0_10_include_hidden_false_include_patterns_i18n_t')hidden: false,
      include_patterns: [
    i18n.t('ui_fallback_patterns_will_be_overridden_by_backend_on_first_use_return_backup_name_agent_zero_backup_timestamp_slice_0_10_include_hidden_false_include_patterns_these_will_be_repli18n.t('ui_nagement_following_agent_zero_ace_editor_patterns_i18n_t')t - Following Agent Zero ACE editor patterns
i18n.t('ui_exclude_patterns_backup_config_compression_level_6_integrity_check_true_editor_management_following_agent_zero_ace_editor_patterns_async_initbackupedi18n.t('ui_t')r_const_container_document_getelei18n.t('ui_i18n_t')i18n_t')t('ui_i18n_t_ui_i18n_t_ui_darkmode')"ii18n.t('ui_editor_settheme_i18n_t')onst_editor_i18n.t('ui_const_dark_localstorage_getitem_i18n_t')'ui_i18n.t('ui_const_dark_localsti18n.t('ui_if_dark_i18n_t')n_t') else {
        editor.i1i18n.t('ui_editor_settheme_i18n_t')i18n_t_ui_ace_theme_i18n.i18n.t('ui_i18n_t_ui_i18n_t')e_i18n_t')ssion.setMode("i18n.t(i18n.t('ui_th_default_backup_metadata_i18n_t')i18n.t('ui_include_hidden_false_include_patterns_i18n_t_ui_fallback_patterns_will_be_overridden_by_backend_on_first_use_return_backup_name_agent_zero_backup_timestamp_slice_0_10_include_hidden_false_include_patterns_these_will_be_replaced_with_resolved_absolute_paths_by_backend_i18n_t_nagement_following_agent_zero_ace_editor_patterns_i18n_t_ui_exclude_patterns_backup_config_compression_level_6_integrity_check_true_editor_management_following_agent_zero_ace_editor_patterns_async_initbackupeditor_const_container_document_getelementbyid_i18n_t_t_ui_i18n_t_ui_i18n_t_ui_darkmode_i18n_t_ui_if_container_const_editor_ace_edit_i18n_t_editor_settheme_i18n_t_ui_i18n_t_ui_const_dark_localstorage_getitem_i18n_t_else_editor_i18n_t_ui_if_dark_i18n_t_i18n_t_ui_ace_theme_i18n_t_ui_editor_settheme_i18n_t_ssion_setmode_i18n_t_ui_i18n_t_ui_i18n_t_ui_else_editor_settheme_i18n_t_th_default_backup_metadata_i18n_t_ui_editor_session_setmode_i18n_t_metadata_editor_seti18n_t_ui_initialize_with_default_backup_metadata_const_defaultmetadata_await_this_getdefaultbackupmetadata_editor_setvalue_json_stringify_defaultmetadata_null_2_editor_clearselection_auto_update_preview_on_changes_debounced_let_timeout_editor_on_i18n_t_ui_cleartimeout_timeout_timeout_settimeout_this_updatepreview_1000_this_backupeditor_editor_async_initrestoreeditor_const_container_document_getelementbyid_i18n_t_ore_metadata_editor_const_i18n_t_ui_if_container_const_editor_ace_edit_i18n_t_mode_if_dark_i18n_t_ui18n_t_ui_const_dark_localstorage_getitem_i18n_t_i18n_t_ui_preview_error_error_message_ui_if_dark_i18n_t_ark_elsi18n_t_ui_editor_settheme_i18n_t_i_i18n_t_ui_i18n_t_ui_ace_theme_tomoi18n_t_ui_else_editor_settheme_i18n_t_n_t_ui_i18n_t_ui_i18n_t_ui_ace_mi18n_t_ui_editor_session_setmode_i18n_t_itor_clearselection_i18n_t_ui_editor_setvalue_chani18n_t_ui_editor_clearselection_auto_validate_json_on_changes_editor_on_thii18n_t_ui_this_validaterestoremetadai18n_t_ui_pattern_toreeditor_editor_unified_editor_value_getter_following_mcp_servers_pattern_geteditorvalue_const_editor_this_mode_editor_i18n_t_ui_this_backupeditor_this_restoreeditor_return_editor_editor_getvalue_n_i18n_t_ui_unified_json_formatting_following_mcp_servers_pattern_formatjson_const_editor_this_mode_turn_i18n_t_ui_this_backupeditor_this_restoreeditor_if_editor_return_try_const_currentcontent_editor_getvalue_const_parsed_json_parse_currentcontent_const_formatted_json_stringify_parsed_null_2_editor_setvalue_formatted_editor_clearselection_editor_navigatefilestart_catch_error_console_error_i18n_t_rror_i18n_t_ui_i18n_t_ui_i18n_t_i18n_t_ui_error_this_error_i18n_t_enhanced_filei18n_t_ui_error_message_enhanced_file_preview_operations_async_updatepreview_try_const_meti18n_t_ui_invalid_backup_metadata_error_message_ata_json_parse_metadatatext_if_metadata_include_patterns_metadata_include_patterns_length_0_this_previewstats_total_0_truncated_false_this_previewfiles_this_previewgroups_return_convert_patterns_arrays_back_to_string_format_for_api_const_patternsstring_this_convertpatternstostring_metadata_include_patterns_metadata_exclude_patterns_get_grouped_preview_for_better_ux_const_response_await_sendjsondata_i18n_t_patterns_patternsstring_i18n_t_ui_patterns_patternsstring_include_hidden_metadata_include_hidden_false_max_depth_3_search_filter_this_filesearchfilter_if_response_success_this_previewgroups_response_groups_this_previewstats_response_stats_flatten_groups_for_flat_view_this_previewfiles_response_groups_foreach_group_this_previewfiles_push_group_files_this_applyfilesearch_else_this_error_response_error_catch_error_this_error_preview_error_error_message_convert_pattern_arrays_to_string_format_for_backend_api_convertpatternstostring_includepatterns_excludepatterns_const_patterns_add_include_patterns_if_includepatterns_patterns_push_includepatterns_add_exclude_patterns_with_i18n_t_ui_prefix_if_excludepatterns_excludepatterns_foreach_pattern_patterns_push_pattern_return_patterns_join_metai18n_t_ui_validation_for_backup_metadata_validatebackupmetadata_try_const_metadatatext_this_geteditorvalue_const_metadata_json_parse_metadatatext_validate_required_fields_if_array_isarray_metadata_include_patterns_throw_new_error_if_array_isarray_metai18n_t_ui_if_array_isarray_metadata_exclude_patterns_throw_new_error_if_metadata_backup_nai18n_t_ui_if_metadata_backup_name_typeof_metadata_backup_name_kup_namei18n_t_ui_throw_new_error_this_backupmetadataconi18n_t_ui_this_backupmetadataconfig_metadata_this_error_r_i18n_t_ui_return_true_catch_error_this_error_invalid_backup_metadata_error_message_return_false_file_preview_ui_management_initfilepreview_this_filesearchfilter_ti18n_t_ui_this_expandedgroups_clear_this_previewmode_localstorage_getitem_togglepreviewmodi18n_t_ui_thisi18n_t_ui_togglepreviewmode_this_previewmode_this_previewmode_lstorage_i18n_t_ui_item_i18n_t_ui_kuppreviei18n_t_ui_localstorage_setitem_togglegroupi18n_t_ui_this_previewmode_togglegroup_grouppath_if_this_expandedgroups_has_grouppath_this_expandedgroups_delete_grouppath_else_this_expandedgroups_add_grouppath_isgroupexpanded_grouppath_return_this_expandedgroups_has_grouppath_debouncefilesearch_cleartimeout_this_searchtimeout_this_searchtimeout_settimeout_this_applyfilesearch_300_clearfilesearch_this_filesearchfilter_api18n_t_ui_this_applyfilesearch_applyfilesearch_if_this_filesearchfilter_trim_this_filteredpreviewfiles_this_previewfiles_else_const_search_this_filesearchfilter_tolowercase_this_filteredpreviewfiles_this_previewfiles_filter_file_file_path_tolowercase_includes_search_async_exportfilelist_const_filelist_this_previewfiles_map_f_f_path_join_st_i18n_t_ui_const_blob_new_blob_filelist_type_ateobjecturli18n_t_ui_const_url_url_createobjecturl_blob_coni18n_t_ui_metadata_backup_name_zip_bi18n_t_ui_a_href_url_a_download_url_revokeobjecturli18n_t_ui_a_click_url_revokeobjecturl_url_async_copyfilelisttoclipboard_const_filelist_this_previewfiles_map_f_f_path_join_lipbi18n_t_ui_try_await_navigator_clipboard_writetext_filelist_window_toastfrontendinfo_ard_catch_error_i18n_t_ui_window_toi18n_t_ui_catch_error_window_toastfrontenderror_d_error_bi18n_t_ui_kup_creation_usini18n_t_ui_backup_creation_using_direct_api_call_async_createbackup_validate_i18n_t_ui_backup_creation_failed_response_status_response_statustext_his_loading_true_this_error_i18n_t_ui_thi18n_t_ui_error_this_error_ns_this_addfileoperation_onst_metadata_this_backupmei18n_t_ui_backup_error_error_message_backupmetadataconfig_use_fetch_i18n_t_ui_error_error_message_reate_returns_a_file_download_not_json_const_response_await_fetchapi_t_headi18n_t_ui_method_api18n_t_ui_headers_body_jsi18n_t_ui_stringify_i18n_t_ui_body_json_stringify_include_patterns_metadata_include_patterns_exclude_patterns_metadata_exclude_patterns_include_hidden_metadata_include_hidden_false_backup_name_metadata_backup_name_if_response_ok_handle_file_download_const_blob_await_response_blob_const_url_window_url_createobjecturl_blob_const_a_document_createelement_wnli18n_t_ui_a_href_url_a_downi18n_t_ui_backupname_zip_kup_name_zip_a_click_window_url_revokeobjecturl_url_this_addfileoperation_lly_window_toastfrontendinfo_baci18n_t_ui_window_toastfrontendinfo_lly_backup_status_else_i18n_t_ui_try_to_parsi18n_t_ui_else_try_to_parse_error_response_const_errortext_await_response_text_try_const_errorjson_json_parse_errortext_this_error_errorjson_error_h_this_errori18n_t_ui_catch_this_error_backup_creation_failed_response_status_response_statustext_this_addfileoperation_error_this_error_catch_error_this_error_backup_error_error_message_this_addfileoperation_error_error_message_finally_this_loading_false_async_downloadbackup_backuppath_backupname_try_const_response_await_fetchapi_ost_headi18n_t_ui_method_api18n_t_ui_headers_body_jsi18n_t_ui_stringify_backui18n_t_ui_body_json_stringify_backup_path_backuppath_if_response_ok_const_blob_await_response_blob_const_url_window_url_createobjecturl_blob_const_a_document_createelement_wnli18n_t_ui_a_href_url_a_download_backupname_zip_a_click_window_url_revokeobjecturl_url_catch_error_console_error_cancelbackup_i18n_t_ui_error_cancelbackup_if_this_progresseventsource_this_progresseventsource_close_this_progresseventsource_null_this_loading_false_this_progressdata_null_resettodefaults_this_getdefaultbackupmetadata_then_defaultmetadata_if_this_backupeditor_this_backupeditor_setvalue_json_stringify_defaultmetadata_null_2_this_backupeditor_clearselection_this_updatepreview_dry_run_functionality_async_dryrun_if_this_mode_p_i18n_t_ui_await_this_di18n_t_ui_found_response_files_length_files_that_would_be_backed_up_dryrunrestore_async_dryrunbackup_validate_backup_metadata_first_if_this_validatebackupi18n_t_ui_index_1_file_path_this_formatfilesize_file_size_leoperations_i18n_t_ui_this_clearfileopi18n_t_ui_ntotal_response_files_length_files_this_formatfilesize_response_files_reduce_sum_f_sum_f_size_0_st_patternsstring_this_convertpatternstostring_metadata_include_patterns_metadata_exclude_patterns_const_response_await_sendjsondata_i18n_t_pai18n_t_ui_error_response_error_include_hidden_metadata_include_hidden_fali18n_t_ui_dry_run_error_error_message_if_response_succi18n_t_ui_error_error_message_fileoperation')eration(`\nTotal: ${response.files.length} files, ${this.formati18n.t('ui_response_files_foreach_file_index_this_addfileoperation')Operation('Dry run coi18n.t('ui_dry_run_completed_successfullyi1i18n.t('ui_this_addfileoperation').t('ui_s_error_response_error_this_addfileoperation_error_response_error_catch_error_this_error_dry_run_error_error_mi18n.t('ui_this_addfileoperation_dry_run_completed_successfullyi18n_t_ui_dry_run_completed_successfully_s_error_response_error_this_addfileoperation')se_i18n.t('ui_please_seleci18n.t('ui_catch_error_this_error')this.loadingMessage = 'Performingi18n.t('ui_this_addfileoperation')dry_run')i_performi18n.t(i18n.t('ui_finally_this_loading_false_async_dryrunrestore_if_this_backupfile_this_error_please_select_a_backup_file_fii18n_t_ui_please_select_a_backup_file_first_y_this_loading_true_this_loadingmessage_performing_restore_dry_run_i18n_t_ui_performing_restore_dryi18n_t_ui_clean_before_restore_result_files_to_delete_length_files_would_be_deleted_ui_starting_restore_dry_run_w_formdata_formdata_append_backup_file_this_backupfile_i1i18n_t_ui_index_1_delete_file_path_metadata_this_geteditorvaluei18n_t_ui_metadata_formdata_append_overwrite_policy_this_overwri18n_t_ui_overwrite_policy_formdata_append_clean_before_restore_this_cli18n_t_ui_clean_before_restori18n_t_ui_result_files_to_restore_length_files_would_be_restored_preview_i18n_t_ui_backup_restore_preview_body_formdata_i18n_t_ui_post_i18n_t_ui_index_1_restore_file_original_path_file_target_path_show_delete_operations_if_clean_before_restore_is_enabled_if_result_files_to_delete_result_files_to_delete_length_0_this_addi18n_t_ui_nskipped_result_skipped_files_length_files_files_to_delete_length_files_would_be_deleted')        this.addFileOperation('');
       i18n.t('ui_show_restore_operations_if_result_files_to_restore_result_files_to_restore_lengti18n.t('ui_this_addfileoperation_show_restore_operations_if_result_files_to_restore_result_files_to_restore_length_0_this_addfileoperi18n_t_ui_nsummary_deletecount_to_delete_restorecount_to_restore_skippedcount_skipped_les_to_restore_foreach_file_index_this_addfileoperation')is_ai18n_t')error_message')ped ${result.skipped_files.length} files:`i18n.t('ui_i18n_t_ui_error_result_error_show_skipped_files_if_result_skippi18n_t_ui_dry_run_error_error_message_s_length_0_this_ai18n_t_ui_error_error_message_ped_result_skipped_files_length_files')   const restoreCount = result.restore_count || 0;
        const skippedCount = result.skipped_fii18n.t('ui_index_1_file_original_path_file_reason')Summary: ${deleteCount} to delete, ${restoreCount} to restore, ${skippedCount} skipped`);
        this.addFileOperation('Dry run coi18n.t('ui_dry_run_completed_successfullyi18n_t')n_completed_successfully')s.error =i18n.t('ui_s_error_ri18n.t('ui_nsummary_deletecount_to_delete_restorecount_to_restore_skippedcount_skipped')r_error_message_this_addfileoperation_error_error_message_finally_this_loading_false_enhanced_restore_operations_with_metadata_display_async_handlefileupload_eventi18n.t('ui_error_result_error')et_files_0_if_file_return_this_backupfile_file_this_eri18n.t('ui_dry_run_error_error_message')esult_nuli18n_t')estoreresult_nui18n.t('ui_error_error_message')e_this_loadingmessage');

      i18n.t('ui_const_formdata_new_i18n_t')formdata_new_formdata_formdata_append')onst respi18n.t('ui_onst_responsei18n_t')n.t('ui_inspecti18n.t('ui_inspection_error_error_message')OST',
  ii18n.t('ui_post')t('ui_method'i18n.t('ui_method')8n.t('ui_body_foi18n.t('ui_body_formdata_const_result_await_response_json_if_result_success_this_backupmetadata_result_metadata_load_complete_metadata_for_json_editing_this_restoremetadata_json_parse_json_stringify_result_metadata_deep_copy_initialize_restore_editor_with_complete_metadata_json_if_this_restoreeditor_this_restoreeditor_setvalue_json_stringify_this_restoremetadata_null_2_this_restoreeditor_clearselection_validate_backup_compatibility_this_validatebackupcompatibility_else_this_error_result_error_this_backupmetadata_null_catch_error_this_error_inspection_error_error_message_ti18n_t')_created_with_agent_zero_backupversion_current_version_is_currentversion')s_backupmi18n.t('ui_s_backupmetadata_return_const_warnings_check_agent_zero_version_compatibility_note_both_backup_and_current_versions_are_obtained_via_git_get_git_info_const_backupversion_this_backupmetadata_agent_zero_version_const_currentversion_i1i18n_t')_is_math_floor_dayssincebackup_days_old')from_git_i18n.t('ui_from_git_get_git_info_on_backend_if_backupversion_currentversion_backupversion_i18n_t')lopment')") {
    i18n.t('ui_i18n_t')gs_push_backup_created_with_agent_zero_backupversion_current_version_is_currentversion_check_backup_age_const_backupdate_new_date_this_baci18n.t('ui_compatii18n.t('ui_compatibility_warnings_warnings_join')ackupdate_1000_60_60_24_if_dayssincebackup_30_warnings_push_backup_is_math_floor_dayssincebackup_days_old_check_system_compatibility_const_systeminfo_this_backupmetadata_system_info_if_systeminfo_systeminfo_system_could_add_platform_specific_warnings_here_if_warnings_length_0_window_toastfrontendwarning_compatibility_warnings_warnings_join')Backi18n.i18n.t('ui_backi18n_t')ibilii18n.t('ui_mpatibility') i18n.t('ui_async_pi18n.t('ui_async_performrestore_if_this_backupfile_this_error')ackup file';
      rei18n.t('ui_rei18n_t')_try_this_loading_true_this_loadingmessage') files...i18n.t('ui_files')hi18n.t('ui_this_eri18n.t('ui_this_error')('ui_this_cli18n.t('ui_this_clearfileoperations_this_addfileoperation')toration...');

      i18n.t('ui_i18n_t')formdata_new_formdata_formdata_append')le', thisi18n.t('ui_le')ci18n.t('ui_this_bai18n.t('ui_this_backupfile_formdata_append')eti18n.t('ui_this_gei18n.t('ui_this_geteditorvalue_formdata_append'), this.ovei18n.t('ui_this_ovei18n_t')verwritepolicy_formdata_append')ore_restoi18n.t('ui_ore_restore')ei18n.t('ui_this_cli18n.t('ui_this_cleanbeforerestore_const_response_await_fetchapi') {
      i18n.t('ui_ii18n_t')before_restore_successfully_deleted_result_deleted_files_length_files')_if_resuli18n.t('ui_if_result_success_log_deleted_files_if_clean_before_restore_was_enabled_if_result_deleted_files_i18n_t')1_deleted_file_path')addfileopi18n.t('ui_addfileoperation_clean_before_restore_successfully_deleted_result_deleted_files_length_files_result_deleted_files_foreach_file_i18n_t')sfully_restored_result_restored_files_length_files')ddfileopei18n.t('ui_ddfileoperation')      // Log restored files
        this.addFileOperation(`Successfuli18n.t('ui_index_1i18n.t('ui_index_1_restored_file_archive_path_file_target_path'i18n.t('ui_successfuli18n_t_ui_index_1_restored_file_archive_path_file_target_path_t_restored_files_foreach_file_index_this_addfileoperation')'ui_nskippei18n.t('ui_nskipped_result_skipped_files_length_files')ulti18n.t('ui_i18n_t_ui_nskipped_result_skipped_files_length_files_if_result_skipped_files_result_skipped_files_length_0_this_addfileoperation')result.skipped_files.forEach((file, index) => {
            this.addFileOperation(`${index + 1}. ${file.original_path} (${file.reasoi18n.t('ui_ni18n.t('ui_index_1_file_original_path_file_reasoi18n_t_ui_nerrors_during_restoration_log_errors_if_result_errors_result_errors_length_0_i18n_t_ui_index_1_error_original_path_error_error')r, index) => {
            this.addFileOperation(`${index + 1}. ${error.original_path}: ${ei18n.t('ui_index_1_error_original_path_error_error')t deletedCount = result.deleted_files?.length || 0;
        const restoredCount = result.restored_files.length;
       i18n.t('ui_nrestori18n.t('ui_nrestore_completed_deletedcount_deleted_restoredcount_restored_skippedcount_skipped_errorcount_errors')addFileOperation(`\nRestore completed: ${deletedCi18n.t('ui_nrestore_completed_deletedcount_deleted_restoredcount_restored_skippedcount_skipped_errorcount_errors')= result;
        window.toastFroi18n.t('ui_error_ri18n.t('ui_error_result_error')i_restorei18n.t('ui_restore_completed_successfully').t('i18n.t('uii18n.t('ui_i18n_t')e_error_error_message')     thisi18n.t('ui_this_error_result_error_i18n_t')error_message')ratii18n.t('ui_error_result_error')_error_result_error_catch_error_this_error_restore_erri18n.t('ui_restore_error_error_message')eration_error_error_message_finai18n.t('ui_error_error_message')json_metadata_utilities_validaterestoremetadata_try_const_metadatatext_this_geteditorvalue_const_metadata_json_parse_metadatatext_i18n_t')amp_message_n')elds
    i18n.t('ui_elds_if_array_isarray_metadata_include_patterns_throw_new_error')ai18n.t('ui_includei18n.t('ui_include_patterns_must_be_an_array')if (!Array.isArray(metadata.exclude_patterns)) {
      i18n.t('ui_invalidi18n.t('ui_invalid_json_metadata_error_message')_patterns_must_be_an_array')}

      i18n.t('ui_this_restoremetadata_metadata_this_error')rei18n.t('ui_rei18n_t')_true_catch_error_this_error_invalid_json_metadata_error_message_return_false_getcurrentrestoremetadata_if_this_validaterestoremetadata_return_this_restoremetadata_return_null_restore_operations_metadata_control_resettooriginalmetadata_if_this_backupmetadata_this_restoremetadata_json_parse_json_stringify_this_backupmetadata_deep_copy_if_this_restoreeditor_this_restoreeditor_setvalue_json_stringify_this_restoremetadata_null_2_this_restoreeditor_clearselection_utility_formattimestamp_timestamp_if_timestamp_return')
    retui18n.t('ui_retui18n_t')_new_date_timestamp_tolocalestring_formatfilesize_bytes_if_bytes_return') consi18ni18n.t('ui_consi18n_t')sizes') 'Mi18n.ti18n.t('ui_')ui_'), 'Gii18n.t('ui_ui').t('ui18n.t('ui_gi18n_t')i18n.i18n.t('ui_i18n_t')i18n.i18n.t('ui_coni18n_t')i_math_floor_mai18n.t('ui_bytes_mi18n.t('ui_bytes_math_pow_1024_i_tofixed_1_sizes_i')ed_1_sizes_i_formatdate_datestring_if_datestring_return')
    retui18n.t('ui_retui18n_t')_new_date_datestring_tolocaledatestring_consi18n.t('ui_agent_zi18n.t('ui_agent_zero_backup_timestamp_slice_0_10')re')", model);
expi18n.t('ui_i18n_t_ui_i18n_t_ui_js_alpinestore_js')om "i18n.t('ui_i18n_t_ui_i18n_t_ui_i18n_t_ui_js_alpinestore_js')";

// Global function references
const sendJsonData = globalThis.sendJsonData;
const toast = globalThis.toast;
const fetchApi = globalThis.fetchApi;

// ⚠️ CRITICAL: The .env file contains API keys and esseni18n.t('ui_i18n_t_ui_js_alpinestore_js')le is REQUIRED for Agent Zero to function and must be backed up.

const model = {
  // State
  mode: 'backup', // 'backup' or 'resti18n.t('ui_agent_zero_backup_timestamp_slice_0_10'),
  error: '',

  // File operations log (shared between backup and restore)
  fileOperationsLog: '',

  // Backup state
  backupMetadataConfig: null,
  includeHidden: i18n.t('ui_backup')
  previ18n.t('ui_backup')ts: { i18n.t('ui_restore')0, truncated: false },
  backupEditor: ni18n.t('ui_error')Eni18n.t('ui_file_operations_log_shared_between_backup_and_restore_fileoperationslog')ili18n.t('ui_backup_state_backupmetadataconfig_null_includehidden_false_previewstats_total_0_truncated_false_backupeditor_null_enhanced_file_preview_state_previewmode')e state
 i18n.t('ui_')upFile: ni18n.t('ui_or')
  baci18n.t('ui_previewfiles_previewgroups_filteredpreviewfiles_filesearchfilter')toi18n.t('ui_expandedgroups_new_set_progress_state_progressdata_null_progresseventsource_null_restore_state_backupfile_null_backupmetadata_null_restorepatterns')  i18n.t('ui_overwritepolicy')view();
  }i18n.t('ui_cleanbeforerestore_false_restoreeditor_null_restoreresult_null_initialization_async_initbackup_this_mode')   this.i18n.t('ui_this_resetstate_await_this_initbackupeditor_await_this_updatepreview_async_initrestore_this_mode')fileOperai18n.t('ui_this_resetstate_await_this_initrestoreeditor_resetstate_this_loading_false_this_error')rii18n.t('ui_this_backupfile_null_this_backupmetadata_null_this_restoreresult_null_this_fileoperationslog')extTick is not available in stores
    setTimeout(() => {
      const textarea = document.getElementById(this.mode === 'backup' ? 'backup-file-list' : 'restore-file-list');
      if (textarea) {
        textarea.scrollTop = textarea.scrollHeight;
      }
    }, 0);
  },

  clearFileOperations() {
    this.fileOperationsLog = '';
  },

  // Cleanup method fori18n.t('ui_backup') closi18n.t('ui_backup_file_list')    ti18n.t('ui_restore_file_list')
    if (this.backupEditor) {
      this.backupEditor.destroy();
      this.backupEditor = null;
    }
    if (this.restoreEditor) {
      this.restoreEditor.dei18n.t('ui_cleanup_method_for_modal_close_onclose_this_resetstate_if_this_backupeditor_this_backupeditor_destroy_this_backupeditor_null_if_this_restoreeditor_this_restoreeditor_destroy_this_restoreeditor_null_get_default_backup_metadata_with_resolved_patterns_from_backend_async_getdefaultbackupmetadata_const_timestamp_new_date_toisostring_try_get_resolved_default_patterns_from_backend_const_response_await_sendjsondata_i18n_t') exclude_patterns = response.defaui18n.t('ui_if_response_success_use_patterns_from_backend_with_resolved_absolute_paths_const_include_patterns_response_default_patterns_include_patterns_const_exclude_patterns_response_default_patterns_exclude_patterns_return_backup_name_agent_zero_backup_timestamp_slice_0_10_include_hidden_false_include_patterns_include_patterns_exclude_patterns_exclude_patterns_backup_config_compression_level_6_integrity_check_true_catch_error_console_warn_i18n_t')ice(0, 10)}`,
      include_hidden: false,
      include_patterns: [
    i18n.t('ui_fallback_patterns_will_be_overridden_by_backend_on_first_use_return_backup_name_agent_zero_backup_timestamp_slice_0_10_include_hidden_false_include_patterns_these_will_be_replaced_with_resolved_absolute_paths_by_backend_i18n_t')nagement - Following Agent Zero ACE editor patterns
i18n.t('ui_exclude_patterns_backup_config_compression_level_6_integrity_check_true_editor_management_following_agent_zero_ace_editor_patterns_async_initbackupeditor_const_container_document_getelementbyid_i18n_t')t('ui_i18n_t_ui_i18n_t_ui_darkmode')"i18n.t('ui_i18n_t_ui_if_container_const_editor_ace_edit_i18n_t_editor_settheme')"i18n.t('ui_i18n.t('ui_const_dark_localstorage_getitem_i18n_t') else {
        editor.i18n.t('ui_if_dark_i18n_t')i18n_t_ui_ace_theme_i18n.t('ui_editor_settheme_i18n_t')ssion.setMode("i18n.t('ui_i18n_t_ui_i18n_t_ui_i18n_t_ui_else_editor_settheme_i18n_t_th_default_backup_metadata_i18n_t_ui_editor_session_setmode_i18n_t_metadata_editor_seti18n_t_ui_initialize_with_default_backup_metadata_const_defaultmetadata_await_this_getdefaultbackupmetadata_editor_setvalue_json_stringify_defaultmetadata_null_2_editor_clearselection_auto_update_preview_on_changes_debounced_let_timeout_editor_on_i18n_t_ui_cleartimeout_timeout_timeout_settimeout_this_updatepreview_1000_this_backupeditor_editor_async_initrestoreeditor_const_container_document_getelementbyid_i18n_t_ore_metadata_editor')");

      const i18n.t('ui_if_container_const_editor_ace_edit_i18n_t')mode')"i18n.t('ui_if_dark')"i18n.t('ui18n.t('ui_const_dark_localstorage_getitem_i18n_t')i18n.t('ui_preview_error_error_message')ui_if_dark_i18n_t')ark')"i18n.t('ui_elsi18n_t_ui_editor_settheme_i18n_t_i_i18n_t_ui_i18n_t_ui_ace_theme_tomoi18n_t_ui_else_editor_settheme_i18n_t_n_t_ui_i18n_t_ui_i18n_t_ui_ace_mi18n_t_ui_editor_session_setmode_i18n_t_itor_clearselection_i18n_t_ui_editor_setvalue_chani18n_t_ui_editor_clearselection_auto_validate_json_on_changes_editor_on_thii18n_t_ui_this_validaterestoremetadai18n_t_ui_pattern_toreeditor_editor_unified_editor_value_getter_following_mcp_servers_pattern_geteditorvalue_const_editor_this_mode_editor_i18n_t_ui_this_backupeditor_this_restoreeditor_return_editor_editor_getvalue_n_i18n_t_ui_unified_json_formatting_following_mcp_servers_pattern_formatjson_const_editor_this_mode_turn_i18n_t_ui_this_backupeditor_this_restoreeditor_if_editor_return_try_const_currentcontent_editor_getvalue_const_parsed_json_parse_currentcontent_const_formatted_json_stringify_parsed_null_2_editor_setvalue_formatted_editor_clearselection_editor_navigatefilestart_catch_error_console_error_i18n_t_rror')"i18n.t('ui_i18n_t_ui_i18n_t_i18n.t('ui_error_this_error_i18n_t') }
  },

  // Enhanced Filei18n.t('ui_error_message_enhanced_file_preview_operations_async_updatepreview_try_const_meti18n.t('ui_invalid_backup_metadata_error_message')ata_json_parse_metadatatext_if_metadata_include_patterns_metadata_include_patterns_length_0_this_previewstats_total_0_truncated_false_this_previewfiles_this_previewgroups_return_convert_patterns_arrays_back_to_string_format_for_api_const_patternsstring_this_convertpatternstostring_metadata_include_patterns_metadata_exclude_patterns_get_grouped_preview_for_better_ux_const_response_await_sendjsondata_i18n_t') {
        patterns: patternsString,
i18n.t('ui_patterns_patternsstring_include_hidden_metadata_include_hidden_false_max_depth_3_search_filter_this_filesearchfilter_if_response_success_this_previewgroups_response_groups_this_previewstats_response_stats_flatten_groups_for_flat_view_this_previewfiles_response_groups_foreach_group_this_previewfiles_push_group_files_this_applyfilesearch_else_this_error_response_error_catch_error_this_error_preview_error_error_message_convert_pattern_arrays_to_string_format_for_backend_api_convertpatternstostring_includepatterns_excludepatterns_const_patterns_add_include_patterns_if_includepatterns_patterns_push_includepatterns_add_exclude_patterns_with')   i18n.t('ui_prefix_if_excludepatterns_excludepatterns_foreach_pattern_patterns_push_pattern_return_patterns_join')metai18n.t('ui_validation_for_backup_metadata_validatebackupmetadata_try_const_metadatatext_this_geteditorvalue_const_metadata_json_parse_metadatatext_validate_required_fields_if_array_isarray_metadata_include_patterns_throw_new_error')    }
      if (!Array.isArray(metai18n.t('ui_if_array_isarray_metadata_exclude_patterns_throw_new_error')    }
      if (!metadata.backup_nai18n.t('ui_if_metadata_backup_name_typeof_metadata_backup_name')kup_namei18n.t('ui_throw_new_error'));
      }

      this.backupMetadataConi18n.t('ui_this_backupmetadataconfig_metadata_this_error')r)i18n.t('ui_return_true_catch_error_this_error_invalid_backup_metadata_error_message_return_false_file_preview_ui_management_initfilepreview_this_filesearchfilter') ti18n.t('ui_this_expandedgroups_clear_this_previewmode_localstorage_getitem')
  togglePreviewModi18n.t('ui_')
    thisi18n.t('ui_togglepreviewmode_this_previewmode_this_previewmode')lStorage.i18n.t('ui_')Item('i18n.t('ui_')kupPreviei18n.t('ui_localstorage_setitem')  },

  toggleGroupi18n.t('ui_this_previewmode_togglegroup_grouppath_if_this_expandedgroups_has_grouppath_this_expandedgroups_delete_grouppath_else_this_expandedgroups_add_grouppath_isgroupexpanded_grouppath_return_this_expandedgroups_has_grouppath_debouncefilesearch_cleartimeout_this_searchtimeout_this_searchtimeout_settimeout_this_applyfilesearch_300_clearfilesearch_this_filesearchfilter')api18n.t('ui_this_applyfilesearch_applyfilesearch_if_this_filesearchfilter_trim_this_filteredpreviewfiles_this_previewfiles_else_const_search_this_filesearchfilter_tolowercase_this_filteredpreviewfiles_this_previewfiles_filter_file_file_path_tolowercase_includes_search_async_exportfilelist_const_filelist_this_previewfiles_map_f_f_path_join')st],i18n.t('ui_const_blob_new_blob_filelist_type')ateObjectURLi18n.t('ui_const_url_url_createobjecturl_blob_coni18n.t('ui_metadata_backup_name_zip')') 'bi18n.t('ui_a_href_url_a_download')   URL.revokeObjectURLi18n.t('ui_a_click_url_revokeobjecturl_url_async_copyfilelisttoclipboard_const_filelist_this_previewfiles_map_f_f_path_join')lipbi18n.t('ui_try_await_navigator_clipboard_writetext_filelist_window_toastfrontendinfo')ard');
    } catch (error) {
  i18n.t('ui_')  window.toi18n.t('ui_catch_error_window_toastfrontenderror')d Error');
    }
  },

  // Bi18n.t('ui_')kup Creation usini18n.t('ui_backup_creation_using_direct_api_call_async_createbackup_validate_i18n.t('ui_backup_creation_failed_response_status_response_statustext')his_loading_true_this_error')  i18n.t('ui_thi18n.t('ui_error_this_error')ns_this_addfileoperation')onst metadata = this.backupMei18n.t('ui_backup_error_error_message')_backupmetadataconfig_use_fetch_i18n.t('ui_error_error_message')reate_returns_a_file_download_not_json_const_response_await_fetchapi')T',
        headi18n.t('ui_method')': 'api18n.t('ui_headers')      body: JSi18n.t('ui_').stringify({
     i18n.t('ui_body_json_stringify_include_patterns_metadata_include_patterns_exclude_patterns_metadata_exclude_patterns_include_hidden_metadata_include_hidden_false_backup_name_metadata_backup_name_if_response_ok_handle_file_download_const_blob_await_response_blob_const_url_window_url_createobjecturl_blob_const_a_document_createelement')wnli18n.t('ui_a_href_url_a_downi18n.t('ui_backupname_zip')kup_name_zip_a_click_window_url_revokeobjecturl_url_this_addfileoperation')lly!');
        window.toastFrontendInfo('Baci18n.t('ui_window_toastfrontendinfo')lly', 'Backup Status');
      } else {
     i18n.t('ui_') // Try to parsi18n.t('ui_else_try_to_parse_error_response_const_errortext_await_response_text_try_const_errorjson_json_parse_errortext_this_error_errorjson_error')h {
          this.errori18n.t('ui_catch_this_error_backup_creation_failed_response_status_response_statustext_this_addfileoperation_error_this_error_catch_error_this_error_backup_error_error_message_this_addfileoperation_error_error_message_finally_this_loading_false_async_downloadbackup_backuppath_backupname_try_const_response_await_fetchapi')OST',
        headi18n.t('ui_method')': 'api18n.t('ui_headers')      body: JSi18n.t('ui_').stringify({ backui18n.t('ui_body_json_stringify_backup_path_backuppath_if_response_ok_const_blob_await_response_blob_const_url_window_url_createobjecturl_blob_const_a_document_createelement')wnli18n.t('ui_a_href_url_a_download_backupname_zip_a_click_window_url_revokeobjecturl_url_catch_error_console_error') cancelBackup() {i18n.t('ui_error_cancelbackup_if_this_progresseventsource_this_progresseventsource_close_this_progresseventsource_null_this_loading_false_this_progressdata_null_resettodefaults_this_getdefaultbackupmetadata_then_defaultmetadata_if_this_backupeditor_this_backupeditor_setvalue_json_stringify_defaultmetadata_null_2_this_backupeditor_clearselection_this_updatepreview_dry_run_functionality_async_dryrun_if_this_mode')p();
   i18n.t('ui_await_this_di18n.t('ui_found_response_files_length_files_that_would_be_backed_up')_dryrunrestore_async_dryrunbackup_validate_backup_metadata_first_if_this_validatebackupi18n.t('ui_index_1_file_path_this_formatfilesize_file_size')leOperations();
    i18n.t('ui_this_clearfileopi18n.t('ui_ntotal_response_files_length_files_this_formatfilesize_response_files_reduce_sum_f_sum_f_size_0')st_patternsstring_this_convertpatternstostring_metadata_include_patterns_metadata_exclude_patterns_const_response_await_sendjsondata_i18n_t'){
        pai18n.t('ui_error_response_error')        include_hidden: metadata.include_hidden || fali18n.t('ui_dry_run_error_error_message')    });

      if (response.succi18n.t('ui_error_error_message')FileOperation(`Found ${response.files.length} files that would be backed up:`);
        response.files.forEach((file, index) => {
          this.addFileOperation(`${index + 1}. ${file.path} (${this.formatFileSize(file.size)})`);
        });
        this.addFileOperation(`\nTotal: ${response.files.length} files, ${this.formatFileSize(response.files.reduce((sum, f) => sum + f.size, 0))}`);
        this.addFileOperation('Dry run completed successfullyi18n.t('ui_dry_run_completed_successfully')s.error = response.error;
        this.addFileOperation(`Error: ${response.error}`);
      }
    } catch (error) {
      this.error = `Dry run error: ${error.message}`;
      this.addFileOperation(`Error: ${error.message}`);
    } finally {
      this.loading = false;
    }
  },

  async dryRunRestore() {
    if (!this.backupFile) {
      this.error = 'Please select a backup file fii18n.t('ui_please_select_a_backup_file_first')y {
      this.loading = true;
      this.loadingMessage = 'Performing restore dry run...'i18n.t('ui_performing_restore_dryi18n.t('ui_clean_before_restore_result_files_to_delete_length_files_would_be_deleted')'ui_starting_restore_dry_run')w FormData();
      formData.append('backup_file', this.backupFile)i1i18n.t('ui_index_1_delete_file_path')('metadata', this.getEditorValuei18n.t('ui_metadata')   formData.append('overwrite_policy', this.overwri18n.t('ui_overwrite_policy')  formData.append('clean_before_restore', this.cli18n.t('ui_clean_before_restori18n.t('ui_result_files_to_restore_length_files_would_be_restored')preview', {
  i18n.t('ui_backup_restore_preview')       body: formData
i18n.t('ui_post')  });

     i18n.t('ui_index_1_restore_file_original_path_file_target_path')
        // Show delete operations if clean before restore is enabled
        if (result.files_to_delete && result.files_to_delete.length > 0) {
          this.addi18n.t('ui_nskipped_result_skipped_files_length_files')files_to_delete.length} files would be deleted:`);
          result.files_to_delete.forEach((filei18n.t('ui_index_1_file_original_path_file_reason')ndex + 1}. DELETE: ${file.path}`);
          });
          this.addFileOperation('');
        }

        // Show restore operations
        if (result.files_to_restore && result.files_to_restore.length > 0) {
          this.addFileOperi18n.t('ui_nsummary_deletecount_to_delete_restorecount_to_restore_skippedcount_skipped')les_to_restore.forEach((file, index) => {
            this.addFileOperation(`${index + 1}. RESTORE: ${file.original_path} -> ${file.target_path}`);
   i18n.t('ui_error_result_error')        // Show skipped files
        if (result.skippi18n.t('ui_dry_run_error_error_message')s.length > 0) {
          this.ai18n.t('ui_error_error_message')ped ${result.skipped_files.length} files:`);
          result.skipped_files.forEach((file, index) => {
            this.addFileOperation(`${index + 1}. ${file.original_path} (${file.reason})`);
          });
        }

        const deleteCount = result.delete_count || 0;
        const restoreCount = result.restore_count || 0;
        const skippedCount = result.skipped_files?.length || 0;

        this.addFileOperation(`\nSummary: ${deleteCount} to delete, ${restoreCount} to restore, ${skippedCount} skipped`);
        this.addFileOperation('Dry run completed successfullyi18n.t('ui_dry_run_completed_successfully')s.error = result.error;
        this.addFileOperation(`Error: ${result.error}`);
      }
    } catch (error) {
      this.error = `Dry run error: ${error.message}`;
      this.addFileOperation(`Error: ${error.message}`);
    } finally {
      this.loading = false;
    }
  },

  // Enhanced Restore Operations with Metadata Display
  async handleFileUpload(event) {
    const file = event.target.files[0];
    if (!file) return;

    this.backupFile = file;
    this.error = '';
    this.restoreResult = nuli18n.t('ui_this_restoreresult_null_try_this_loading_true_this_loadingmessage');

      const formData = new i18n.t('ui_const_formdata_new_formdata_formdata_append')onst responsei18n.t('ui_fili18n.t('ui_inspection_error_error_message')thod: 'POST',
  i18n.t('ui_method')
     i18n.t('ui_body_formdata_const_result_await_response_json_if_result_success_this_backupmetadata_result_metadata_load_complete_metadata_for_json_editing_this_restoremetadata_json_parse_json_stringify_result_metadata_deep_copy_initialize_restore_editor_with_complete_metadata_json_if_this_restoreeditor_this_restoreeditor_setvalue_json_stringify_this_restoremetadata_null_2_this_restoreeditor_clearselection_validate_backup_compatibility_this_validatebackupcompatibility_else_this_error_result_error_this_backupmetadata_null_catch_error_this_error_inspection_error_error_message_ti18n.t('ui_backup_created_with_agent_zero_backupversion_current_version_is_currentversion')s_backupmetadata_return_const_warnings_check_agent_zero_version_compatibility_note_both_backup_and_current_versions_are_obtained_via_git_get_git_info_const_backupversion_this_backupmetadata_agent_zero_version_const_currentversion_i1i18n.t('ui_backup_is_math_floor_dayssincebackup_days_old')from_git_get_git_info_on_backend_if_backupversion_currentversion_backupversion_i18n_t')_ui_development')") {
    i18n.t('ui_warnings_push_backup_created_with_agent_zero_backupversion_current_version_is_currentversion_check_backup_age_const_backupdate_new_date_this_baci18n.t('ui_compatibility_warnings_warnings_join')te_now_backupdate_1000_60_60_24_if_dayssincebackup_30_warnings_push_backup_is_math_floor_dayssincebackup_days_old_check_system_compatibility_const_systeminfo_this_backupmetadata_system_info_if_systeminfo_systeminfo_system_could_add_platform_specific_warnings_here_if_warnings_length_0_window_toastfrontendwarning_compatibility_warnings_warnings_join')Backi18n.t('ui_')mpatibility');
    }
 i18n.t('ui_async_performrestore_if_this_backupfile_this_error')lect a backup file';
      rei18n.t('ui_return_try_this_loading_true_this_loadingmessage') files...';
      thi18n.t('ui_this_error')thi18n.t('ui_this_clearfileoperations_this_addfileoperation')file restoration...');

      i18n.t('ui_const_formdata_new_formdata_formdata_append')le', this.baci18n.t('ui_this_backupfile_formdata_append'), this.geti18n.t('ui_this_geteditorvalue_formdata_append')_policy', this.ovei18n.t('ui_this_overwritepolicy_formdata_append')ore_restore', this.clei18n.t('ui_this_cleanbeforerestore_const_response_await_fetchapi')estore', {
      ii18n.t('ui_clean_before_restore_successfully_deleted_result_deleted_files_length_files')_if_result_success_log_deleted_files_if_clean_before_restore_was_enabled_if_result_deleted_files_i18n.t('ui_index_1_deleted_file_path')addfileoperation_clean_before_restore_successfully_deleted_result_deleted_files_length_files_result_deleted_files_foreach_file_i18n.t('ui_successfully_restored_result_restored_files_length_files')ddfileoperation')   }

        // Log restored files
        this.addFileOperation(`Successfuli18n.t('ui_index_1_restored_file_archive_path_file_target_path')t.restored_files.forEach((file, index) => {
          this.addFileOperation(`${index + 1}. RESTORED: ${file.archive_path} -> ${file.target_path}`);
  i18n.t('ui_nskipped_result_skipped_files_length_files') if (result.skipped_files && result.skipped_files.length > 0) {
          this.addFileOperation(`i18n.t('ui_index_1_file_original_path_file_reason')         result.skipped_files.forEach((file, index) => {
            this.addFileOperation(`${index + 1}. ${file.original_path} (${file.reasoi18n.t('ui_nerrors_during_restoration') }

        // Log errors
        if (result.errors && result.errors.length > 0) {
        i18n.t('ui_index_1_error_original_path_error_error'):`);
          result.errors.forEach((error, index) => {
            this.addFileOperation(`${index + 1}. ${error.original_path}: ${error.error}`);
          });
        }

        const deletedCount = result.deleted_files?.length || 0;
        const restoredCount = result.restored_files.length;
       i18n.t('ui_nrestore_completed_deletedcount_deleted_restoredcount_restored_skippedcount_skipped_errorcount_errors')   this.addFileOperation(`\nRestore completed: ${deletedCount} deleted, ${restoredCount} restored, ${skippedCount} skipped, ${errorCount} errors`);
        this.restoreResult = result;
        window.toastFroi18n.t('ui_error_result_error')18n.t('ui_restore_completed_successfully')e Sti18n.t('i18n.t('ui_restore_error_error_message')     this.error = result.error;
i18n.t('ui_error_error_message')ration(`Error: ${result.error}`);
      }
    } catch (error) {
      this.error = `Restore error: ${error.message}`;
      this.addFileOperation(`Error: ${error.message}`);
    } finally {
      this.loading = false;
    }
  },

  // JSON Metadata Utilities
  validateRestoreMetadata() {
    try {
      const metadataText = this.getEditorValue();
      const metadata = JSON.parse(metadataText);

  i18n.t('ui_timestamp_message_n')elds
      if (!Array.isArray(metadata.include_patterns)) {
        throw new Error('include_pai18n.t('ui_include_patterns_must_be_an_array')}
      if (!Array.isArray(metadata.exclude_patterns)) {
      i18n.t('ui_invalid_json_metadata_error_message')_exclude_patterns_must_be_an_array')}

      this.restoreMetadata = metadata;
      this.error = '';
      rei18n.t('ui_return_true_catch_error_this_error_invalid_json_metadata_error_message_return_false_getcurrentrestoremetadata_if_this_validaterestoremetadata_return_this_restoremetadata_return_null_restore_operations_metadata_control_resettooriginalmetadata_if_this_backupmetadata_this_restoremetadata_json_parse_json_stringify_this_backupmetadata_deep_copy_if_this_restoreeditor_this_restoreeditor_setvalue_json_stringify_this_restoremetadata_null_2_this_restoreeditor_clearselection_utility_formattimestamp_timestamp_if_timestamp_return')
    retui18n.t('ui_return_new_date_timestamp_tolocalestring_formatfilesize_bytes_if_bytes_return') consi18n.t('ui_const_sizes') 'Mi18n.t('ui_'), 'Gi18n.t('ui_')];
 i18n.t('ui_') coni18n.t('ui_const_i_math_floor_mai18n.t('ui_bytes_math_pow_1024_i_tofixed_1_sizes_i')_i_tofixed_1_sizes_i_formatdate_datestring_if_datestring_return')
    retui18n.t('ui_return_new_date_datestring_tolocaledatestring_consi18n.t('ui_agent_zero_backup_timestamp_slice_0_10')ackupstore')", model);
export { store };
