name: Docs Quality

on:
  pull_request:
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "Makefile"
      - ".github/workflows/docs-quality.yml"
  push:
    branches:
      - soma_integration
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "Makefile"
      - ".github/workflows/docs-quality.yml"

jobs:
  lint-links-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: "docs/**/*.md"

      - name: Link check
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: >-
            --no-progress
            --accept "200..299,301,302"
            docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs tooling
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements-docs.txt

      - name: Build MkDocs site
        run: mkdocs build --strict
