name: OpenTelemetry CI

on:
  push:
    branches: [ main, V0.1.1 ]
  pull_request:
    branches: [ main, V0.1.1 ]

jobs:
  otel-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install opentelemetry-sdk opentelemetry-instrumentation-fastapi opentelemetry-exporter-otlp

      - name: Run OTEL instrumentation tests
        run: |
          # Simple sanity check: start the gateway with OTEL env vars and ensure it starts
          export OTEL_TRACES_EXPORTER=console
          export OTEL_METRICS_EXPORTER=none
          python -c "import services.gateway.main as g; print('OTEL import ok')"
