name: Security Checks

on:
  push:
    branches: [ main, V0.1.1 ]
  pull_request:
    branches: [ main, V0.1.1 ]

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety

      - name: Run Bandit (static security analysis)
        run: |
          bandit -r . -ll

      - name: Run Safety (dependency vulnerability check)
        run: |
          safety check --full-report
